.clang-format
include/graph.hpp
include/typelist.hpp
src/main.cpp

Limiting to 100 (plus some slack) typically removes the need for vertical scrolling, making it more readable in GitHub patch reviews, copy&paste to Mattermost, etc. and generally makes reading those long lines easier.
To actually make broken long lines easier to read, enable AlignAfterOpenBracket.
To find function names quickly enable AlwaysBreakAfterReturnType. Especially with long return types (or decl-specifiers) it otherwise can take way too long to find the function name.
Additionally, keep template heads on their own lines. I would equally prefer to have requires clauses on their own lines, but we'd need clang 15.
ChangeLog:
* .clang-format: Change rules to insert readable breaks in otherwise long lines.
* include/graph.hpp: Re-apply clang-format.
* include/typelist.hpp: Ditto.
* …

Try to stay in 100 columns

---

.github/workflows/ci.yml
CMakeLists.txt
src/main.cpp

Add's a CI run compiling to emscripten and running the resulting wasm binary from node.

CI: enable emscripten build

---

include/graph.hpp
include/typelist.hpp
include/vir/detail.h
include/vir/simd.h
include/vir/simd_bit.h
include/vir/simd_bitset.h
include/vir/simd_cast.h
include/vir/simd_float_ops.h
include/vir/simd_resize.h
src/main.cpp

This adds `node::process_batch` showing how to build a generic implementation that builds on specific `process_one` implementations. The implementation detects whether `process_one` can be compiled with `stdx::simd` and whether all inputs and outputs are suitable, in which case it will explicitly vectorize the loop.

Add generic process_batch

---

CMakeLists.txt
bench/CMakeLists.txt
bench/benchmark.hpp
bench/bm_case1.cpp
include/CMakeLists.txt

follows style and re-uses components from
UT: C++20 μ(micro)/Unit Testing Framework by Kris Jusiak (SPDX-License-Identifier: BSL-1.0)
original example, see [here](https://github.com/boost-ext/ut/blob/7c667d99716eb25db3fabb0d9114c8ad46ad7464/example/benchmark.cpp).
The simple use only requires:
```cpp
using namespace boost::ut;
using namespace benchmark;
"string creation1"_benchmark = [] {
std::string created_string{"hello"};
do_not_optimize(created_string);
};
"using marker"_benchmark.repeat<10>() = [] (MarkerMap<"source", "sink1", "sink2", "finish">& marker) {
std::barrier start(3, [&marker] { marker.at<"source">().now(); }); // 1 source + 2 sinks
std::barrier finish(3, [&marker] { marker.at<"finish">().now(); }); // 1 source + 2 sinks
std::jthread source([&start, &finish] { …
```

basic benchmarking facilities

---

include/graph_contracts.hpp

* added a `std::conditional_t<>` statement to remove redundant field declaration. 
* added an in-code documentation to explain the dyn_port design and intended use ... not perfect but hopefully a start.
N.B. the primary idea is to limit the number and breath of public by virtual-inheritance interface and to rely more on strictly-typing, concepts and composition. i.e. dyn_port has (/should) expose only those port interfaces that are necessary from an outside the node/block point-of-view: i.e. connecting with other blocks, exposing information that is required by the runtime scheduler, ...
Further interface definitions should be private and/or accessible only from within the node/block context and should be strictly typed and minimise unnecessary virtual inheritance (<-> performance, …

simplified and added dyn_port documentation

---

include/buffer.hpp
include/buffer_skeleton.hpp
include/circular_buffer.hpp
test/qa_buffer.cpp

... and some minor code-clean ups.
Basic usage (N.B. similar to BufferReader API):
```cpp
// case 1: reserve more than actually written
auto [data, token] = writer.get(4);
for (std::size_t i = 0; i < data.size(); i++) {
data[i] = i + 1;
}
writer.publish(token, 2);
auto read_data = reader.get();
expect(eq(2, read_data.size()));
for (std::size_t i = 0; i < data.size(); i++) {
expect(eq(i + 1, read_data[i])) << "read 1: index " << i;
}
expect(reader.consume(2));
```
N.B. the underlying safety concern of this type of API is that the (expert) user may produce UB if
* token is modified in the user code
* if more samples are published than initially reserved (violates write cursor invariant)
* potentially unsafe in a multiple writer scenario where not all producers publish the exact amount of …

extended BufferWriter API by expert-level get/publish pair

---

.github/workflows/ci.yml

Uses the ubuntu-toolchain [PPA](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/ppa) which provides newer versions of gcc than the ones from the regular repositories.
Switches from `gcc 12.1.0-2ubuntu1~22.04` (the default on ubuntu 22.04LTS jammy) to `gcc 12.2.0-3ubuntu1~22.04`.
The newest ubuntu kinetic 22.10 would also provide gcc 12.2.0-3ubuntu1 and the ubuntu lunar development version provides gcc 12.2.0-10ubuntu1 but there is no offiicial github actions runner image for these releases.

CI: use ubuntu toolchains ppa for gcc 12.2.0

---

bench/bm_case1.cpp
include/utils.hpp

implemented cases include:
* node internally translating T -> native_simd<T> -> T
* cascade doing a 'T -> native_simd<T>' -> simd_processing -> 'native_simd<T> -> T' to amortize the conversion between 'T<->native_simd<T>'
for both 'mult*mult*add' as well as '(mult*mult*add)^10' test cases
Signed-off-by: Ralph J. Steinhagen <r.steinhagen@gsi.de>

added self-contained SIMD tests to bm_case1 benchmarks

---

bench/bm_case1.cpp
include/graph.hpp
include/node.hpp
test/qa_dynamic_port.cpp

- nodes are created with graph::make_node function
- it is no longer needed to specify the graph when making connections

Make graph owner of all nodes

---

bench/bm_case1.cpp
include/README.md
include/node.hpp

Added missing support for non-decimating N-in->N-out mechanic providing bulk access to the input/output data and automatic handling of streaming tags and settings changes:
```cpp
template<typename T, typename R>
struct user_defined_block : node<user_defined_block, IN<T, 0, N_MAX, "in">, OUT<R, 0, N_MAX, "out">> {
T _factor = T{1};
// constuctor setting _factor etc.
[[nodiscard]] constexpr auto process_bulk(std::span<const T> input, std::span<R> output) const noexcept {
std::ranges::transform(input, output.begin(), [this](const T& elem) { return elem * _factor; });
}
};
```
This could be also the basis for most other interpolating/decimating blocks.

added node<T>::process_bulk(std::span<>...) support

---

bench/benchmark.hpp
bench/bm_test_helper.hpp

1. If an inline-asm statement clobbers all memory then we don't see realistic benchmark measurements because the optimizer is inhibited from doing certain optimizations. The result is very different depending on the order. The constexpr cases suffered most because the optimizer was inhibited in every single iteration.
2. The source produces only zero-initialized samples. The optimizer was able to see that. And it may or may not have used that knowledge, rendering all previous results as quasi-random. Use inline asm to only inhibit const-prop, nothing else.
ChangeLog:
* bench/benchmark.hpp (do_not_optimize): Optimal do-not-optimize implementation. Do not invalidate all memory in the process.
* bench/bm_test_helper.hpp (source::process_one): Taint the constructed sample using …

Use do-not-optimize inline-asm for more realistic results

---

include/node.hpp
include/utils.hpp

The process_one functions return void, a value, or a tuple of values. Changing this to always return a tuple from process_one makes implementing process_one harder than acceptable. So take a middle-ground and add a invoke_process_one function that regularizes the return type by wrapping the size 0 and 1 cases into tuples. As a result, the work() implementation, calling invoke_process_one instead of process_one, is much simpler.
include/ChangeLog:
* node.hpp (node::invoke_process_one): New. Calls self().process_one and ensures the return type is a tuple. (node::work): Call invoke_process_one instead of process_one, simplifying the logic, eliminating the constexpr-if branches.
* utils.hpp: Remove dummy_t and invoke_void_wrapped since they are not used anymore.

Simplify work() implementation

---

bench/CMakeLists.txt
bench/bm_case1.cpp
bench/bm_test_helper.hpp
include/node.hpp
include/node_traits.hpp
include/utils.hpp
include/vir/simd.h

some highlights (`-O3 -march=native`):
| Benchmark             | DISABLE_SIMD=1 | DISABLE_SIMD=0 |
| --------------------- | -------------- | -------------- |
| merged src->sink work | 238.1Mops/s    |   5.2Gops/s    |
| merged ^10 - float    |  34.1Mops/s    | 212.4Mops/s    |
| merged ^10 - int      |   9.6Mops/s    |  79.2Mops/s    |

simd simd simd

---

include/utils.hpp

If not, try to be helpful via static_assert message.
include/ChangeLog:
* utils.hpp (indexForName): static_assert that the name exists exactly once.

Ensure indexForName finds exactly one match

---

bench/CMakeLists.txt
bench/benchmark.hpp
bench/bm_buffer.cpp
include/circular_buffer.hpp
include/claim_strategy.hpp
include/sequence.hpp
test/qa_buffer.cpp

A collection of commits that seem to work alright.
Please note, that the new bm_buffer benchmark works for me as defined. However, if you increase the number of samples to process to be larger than the buffer size, then the benchmarks with more than one writer hang. Is the `circular_buffer<int32_t, std::dynamic_extent, ProducerType::Multi>` usage correct for multiple writers?

Size optimizations, code simplifications

---

bench/bm_buffer.cpp
include/buffer.hpp
include/buffer_skeleton.hpp
include/circular_buffer.hpp
include/claim_strategy.hpp
include/node.hpp
test/qa_buffer.cpp
test/qa_dynamic_port.cpp

This addresses two things:
* fix circular_buffer writer split get-partial-publish ... relevant only for single-publisher policy and in case more samples have been allocated than are being published + minor clean-ups sonarlint rightfully complained about
* changed circular buffer writer split  get-publish interface to using RAII 
* single- and multi-producer scenario:
throws a terminal exception in case no data has been published <-> API/programming bug
* multi-producer scenario:
throws a terminal exception in case the amount of data reserved and published isn't identical <-> API/programming bug
Unfortunately, I couldn't make this a compile-time expression that checks for that since 'N claimed' is information that is only available during runtime.
Eventually, I'd like to retire the unsafe …

RAII circular buffer writer split get-publish

---

CMakeLists.txt
include/CMakeLists.txt
include/dataset.hpp

Add an DataSet aggregate datatype. Gnuradio's pmtv library is added via fetchCMake for flexible, domain agnostic representation of metadata.

DataSet aggregate type

---

.clang-format
CMakeLists.txt
bench/bm_case1.cpp
bench/bm_test_helper.hpp
include/circular_buffer.hpp
include/dataset.hpp
include/graph.hpp
include/node.hpp
include/node_traits.hpp
include/port.hpp
include/port_traits.hpp
include/reflection.hpp
include/tag.hpp
include/utils.hpp
test/CMakeLists.txt
test/qa_dynamic_port.cpp
test/qa_tags.cpp

Added tag_t definition and basic stream-tag functionality to the port and node definitions.
```
/**
* @brief 'ports' are interfaces that allows data to flow between blocks in a graph, similar to RF connectors.
* Each block can have zero or more input/output ports. When connecting ports, either a single-step or a two-step
* connection method can be used. Ports belong to a computing domain, such as CPU, GPU, or FPGA, and transitions
* between domains require explicit data conversion.
* Each port consists of a synchronous performance-optimised streaming and asynchronous tag communication component:
*                                                                                      ┌───────────────────────
*         ───────────────────┐ …
```

added handling of stream/message tags

---

include/dataset.hpp

as presented at the last GNU Radio architecture meeting on 2023-03-24. See slides for details ([pdf with animations](https://github.com/fair-acc/opendigitizer/files/11076798/20230316_GNU_Radio_DataSet_API-expanded.pdf), [pdf](https://github.com/fair-acc/opendigitizer/files/11076800/20230316_GNU_Radio_DataSet_API.pdf), [odp](https://github.com/fair-acc/opendigitizer/files/11076799/20230316_GNU_Radio_DataSet_API.odp)):
It was identified that there is no 'one-size-fits-all' solution and that we shall establish a complementary composite type concept of `Packet<T>`->`Tensor<T>`->`DataSet<T>`, that covers ~80% of the use cases, and overlap and extend each other (via C++ concepts):

updated DataSet<T>, Tensor<T>, and Packet<T> definitions

---

CMakeLists.txt

Getting the tests to execute on emscripten without running out of memory.

emscripten: ALLOW_MEMORY_GROWTH=1

---

include/graph.hpp
include/node.hpp
include/settings.hpp
include/tag.hpp
test/CMakeLists.txt
test/qa_settings.cpp

Implemented node settings as public node member fields (<-> PoCo) that can be interacted with 
* directly (default from C++ point-of-view), or via 
* key-value-map (`std::map<std::string, pmtv::pmt, std::less<>>`), that can be interacted via 'setting().set(..)' and 'setting().get(..)'.
Example block implementation:
```cpp
template<typename T>
struct TestBlock : public node<TestBlock<T>> {
IN<T>       in;
OUT<T>      out;
T           scaling_factor = static_cast<T>(1);
std::string  context;
std::int32_t n_samples_max = -1;
float        sample_rate        = 1000.0f;
template<fair::meta::t_or_simd<T> V>
[[nodiscard]] constexpr V
process_one(const V &a) const noexcept {
return a * scaling_factor;
}
};
ENABLE_REFLECTION_FOR_TEMPLATE_FULL((typename T), (fair::graph::setting_test::TestBlock<T>), …
```

basic node setting handling

---

.github/workflows/ci.yml
CMakeLists.txt
include/tag.hpp
src/CMakeLists.txt
test/CMakeLists.txt
test/qa_buffer.cpp
test/qa_dynamic_port.cpp
test/qa_settings.cpp
test/qa_tags.cpp

Runs all registered UT tests. Uses an emscripten enabled ut fork for now (draft PR pending). The tests are run through ctest and automatically use nodejs to run the tests in the emscripten build.
Things that I had to change or work around:
- ut: use fork with `attribute(__constructor__)` patched out because emscripten does not support it for functions with arguments, see https://github.com/boost-ext/ut/pull/565 the problem with upstreaming is that there are a lot of other functions which we do not use that are not trivial to support on emscripten
- ut + clang16: fall back to basic reporter instead of `reporter_junit` because clang16 causes segfaults related to cout redirection
- tag.hpp: remove some constexpr-ness, which is not supported in emscripten
- use ubuntu's nodejs v18, as the …

CI: execute UT unit tests

---

.github/workflows/ci-meson.yml
.gitignore
bench/meson.build
emscripten-build.ini
include/meson.build
meson.build
meson_options.txt
src/meson.build
subprojects/.gitignore
subprojects/README.md
subprojects/boost.ut.wrap
subprojects/cli11.wrap
subprojects/fmt.wrap
subprojects/pmt.wrap
subprojects/refl-cpp.wrap
test/meson.build

This PR adds basic meson build support for graph-prototype (not everything is in place yet that exists in the CMake)
To build:
```bash
cd graph-prototype
meson setup build_meson --buildtype=release
cd build_meson
ninja
```
Issues and TODO

Basic meson build support

---

include/graph.hpp
include/node.hpp
include/settings.hpp
include/utils.hpp
test/qa_settings.cpp

* extended settings support to also include vectors of arithmetics
* extended default node constructor to support initialiser lists and pmt (should make the setup/Python integration more generic)
* this eliminated the need for init(node<T>, pmt-map)
* changed SettingsCtx context to pmt-map
* fixed the optional init(old_map, new_map) interface
Some examples from the [qa_settings](https://github.com/fair-acc/graph-prototype/blob/789a5633913ee0604fc0e7ebb707d079ce9741b8/test/qa_settings.cpp#L286-L297) unit-tests:
https://github.com/fair-acc/graph-prototype/blob/789a5633913ee0604fc0e7ebb707d079ce9741b8/test/qa_settings.cpp#L104-L132
//[..]
https://github.com/fair-acc/graph-prototype/blob/789a5633913ee0604fc0e7ebb707d079ce9741b8/test/qa_settings.cpp#L258-L267 …

std::vector<T> settings- & pmt-map constructor initialiser support

---

bench/CMakeLists.txt
bench/bm_filter.cpp
bench/bm_history_buffer.cpp
include/history_buffer.hpp
test/CMakeLists.txt
test/blocklib/core/filter/time_domain_filter.hpp
test/qa_buffer.cpp
test/qa_filter.cpp

History buffer syntax:
```cpp
gr::history_buffer<int, 5> buffer;
buffer.push_back(1);  // buffer: [1] (size: 1, capacity: 5)
buffer.push_back(2);  // buffer: [1, 2] (size: 2, capacity: 5)
buffer.push_back(3);  // buffer: [1, 2, 3] (size: 3, capacity: 5)
buffer.push_back(4);  // buffer: [1, 2, 3, 4] (size: 4, capacity: 5)
buffer.push_back(5);  // buffer: [1, 2, 3, 4, 5] (size: 5, capacity: 5)
buffer.push_back(6);  // buffer: [2, 3, 4, 5, 6] (size: 5, capacity: 5)
// indexing:
buffer[0];     // value: 6 - unchecked access of last/actual sample
buffer[-1];    // value: 5 - unchecked access of previous sample
// ...
buffer.at(0);  // value: 6 - checked access of last/actual sample
buffer.at(-1); // value: 5 - checked access of last/actual sample
// ...
buffer.get_span(0, 3);  // span: [4, 5, …
```

history_buffer<T> and basic FIR and IIR filter

---

.github/workflows/ci-meson.yml
include/annotated.hpp
include/node.hpp
include/settings.hpp
include/typelist.hpp
include/utils.hpp
test/qa_settings.cpp

This commit introduces a robust, transparent Annotated<T, ...> type wrapper interface, paving the way for user-friendly, embedded, in-code documentation. Here's how it works and how it benefits our development process:
**Transparent Type Wrapper:**
`Annotated<T, ...>` wraps around any type, preserving its behaviour while augmenting it with added meta information. This information can range from documentation and unit info to UI behaviour controls and beyond. The variable type argument accepts any meta-information type, with built-in support for optional `Doc<"...">` and `Unit<"...">` that allow for more detailed (e.g. using mark-down) documentation of blocks, its parameters, and their physical (e.g. SI) units. This flexibility enables user extendability, creating a flexible interface that …

 Annotated<T, ...> interface to enhance in-code block and parameter field documentation

---

include/buffer.hpp
include/buffer_skeleton.hpp
include/circular_buffer.hpp
include/claim_strategy.hpp
include/node.hpp
include/port.hpp
include/sequence.hpp
include/tag.hpp
test/qa_buffer.cpp
test/qa_scheduler.cpp
test/qa_settings.cpp

Remove conversion's warnings and make explicit cast where appropriate.
`std::make_signed_t<std::size>` is used for most of the "index" types and `std::size_t` is used for "size" types.
Initially is was planned to remove warnings only for `circular_buffer` class, but since it has many dependencies, other classes were also changed if needed.
**Benchmark bm_buffer results**
The results slightly differ fromm run to run. Here are the 2 randomly selected example outputs.
**Before updates**
```text
┌─────────────────────────benchmark:─────────────────────────┬──────┬─#N─┬─CTX-SW─┬───CPU cache misses────┬───CPU branch misses───┬─<CPU-I>─┬──min───┬──mean──┬─stddev─┬─median─┬───max───┬─total time─┬─ops/s─┐
│                                                            │ SKIP │    │        │ …
```

Remove conversion's warnings.

---

include/node.hpp
include/settings.hpp
include/thread_pool.hpp
test/qa_settings.cpp

This adds a unique technical identifier for each node created during run-time. The intentional use is to be able to disambiguate between blocks that have been created through cloning and/or for which users set the same `name()` but, for example, require different settings.

unique node 'id' and 'name'

---

include/graph.hpp
include/node.hpp
include/scheduler.hpp
include/settings.hpp
test/qa_settings.cpp

* removed template dependency of settings_base ... needed for type-erasure and run-time polymorphism
* exposed unique_name() & settings(), through run-time type-erased interface ...  needed to allow for type-erased modification of block setting parameter.

enable settings mgmt via 'graph'

---

bench/benchmark.hpp
bench/bm_buffer.cpp
cmake/CompilerWarnings.cmake
include/graph.hpp
include/node.hpp
include/plugin_loader.hpp
include/scheduler.hpp
include/settings.hpp
include/thread_affinity.hpp
include/vir/simd.h
include/wait_strategy.hpp
test/app_plugins_test.cpp
test/plugins/bad_plugin.cpp
test/qa_buffer.cpp
test/qa_dynamic_node.cpp
test/qa_dynamic_port.cpp
test/qa_filter.cpp
test/qa_hier_node.cpp
test/qa_settings.cpp

This commit tries to reduce the number of compiler warnings to zero and performs changes suggested by clang-tidy.
reduction of the number of lines in the respective build steps:
- gcc: 2800 -> 400: all will be fixed by https://github.com/gnuradio/pmt/pull/100, the only one remaining is the node constructor with pmt based settings initialisation. [error message](https://github.com/fair-acc/graph-prototype/actions/runs/5314768958/jobs/9622354105?pr=92#step:10:149)
I had to disable the `maybe-unused` waring in gcc because it triggers a massive amount of false positives in the standard library in combination with asan. There is an open gcc issue that I linked from the line in the cmake where I disabled it.
- clang: 1800 -> 112: caused by 1 [simd related …

Fix compiler warnings and incorporate clang-tidy suggestions

---

CMakeLists.txt
bench/bm_test_helper.hpp
include/node.hpp
include/tag.hpp
include/thread_affinity.hpp
include/utils.hpp
test/blocklib/core/unit-test/tag_monitors.hpp
test/qa_settings.cpp
test/qa_tags.cpp

* added source, monitor, and sink example.
* added basic concepts `HasProcessOneFunction<>`, `HasProcessBulkFunction<>`, and   `HasRequiredProcessFunction<>` for non-templated `process_one`  and `process_bulk` to better enforce/signal user-block implementation requirements
This PR only tackles the user-level tag_t propagation API and has still a corner case that needs to be fixed ... as discussed with @ivan-cukic.

refactored tag_t handling

---

bench/bm_case1.cpp
bench/bm_filter.cpp
bench/bm_scheduler.cpp
include/graph.hpp
include/scheduler.hpp
include/thread_pool.hpp
test/app_grc.cpp
test/qa_dynamic_port.cpp
test/qa_hier_node.cpp
test/qa_scheduler.cpp
test/qa_settings.cpp
test/qa_tags.cpp
test/qa_thread_pool.cpp

Adds basic multi-threaded implementations for the simple scheduling algorithms (simple & breadth-first).
fixes #76

scheduler: add thread pool backed parallel implementation to "simple" and "breadth_first" schedulers

---

cmake/CompilerWarnings.cmake
include/claim_strategy.hpp
include/graph_yaml_importer.hpp
include/port.hpp
include/reflection.hpp
include/scheduler.hpp
include/sequence.hpp
meson.build
test/app_grc.cpp
test/blocklib/core/unit-test/common_nodes.hpp
test/blocklib/core/unit-test/tag_monitors.hpp
test/qa_settings.cpp
test/qa_tags.cpp

The only remaining warning that needed to be masked were:
* in graph_yampl_importer.hpp:
```cpp
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wold-style-cast"
#include <yaml-cpp/yaml.h>
#pragma GCC diagnostic pop
```
-> to be followed up with the yampl-cpp community
* And in tag_monitors.cpp:
```cpp
for (const auto &[key, value] : map) {
// workaround for:
// fmt/core.h:1674:10: warning: possibly dangling reference to a temporary [-Wdangling-reference]
// 1674 |   auto&& arg = arg_mapper<Context>().map(FMT_FORWARD(val));
//      |          ^~~
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdangling-reference"
fmt::print(" {:>5}: {} ", key, value);
#pragma GCC diagnostic pop
}
Thanks a lot for the tremendous preparatory work by @drslebedev and @wirew0rm in the …
```

clean-up some more compiler-warnings & enabled `-Werror`

---

bench/bm_scheduler.cpp
include/scheduler.hpp

Fixes benchmarks that run an existing scheduler repeatedly.

scheduler: have run_and_wait reset a stopped scheduler

---

bench/bm_case1.cpp
bench/bm_scheduler.cpp
include/annotated.hpp
include/data_sink.hpp
include/graph.hpp
include/graph_yaml_importer.hpp
include/node.hpp
include/reflection.hpp
include/settings.hpp
include/tag.hpp
test/app_grc.cpp
test/blocklib/core/filter/time_domain_filter.hpp
test/blocklib/core/unit-test/common_nodes.hpp
test/blocklib/core/unit-test/tag_monitors.hpp
test/grc/test.grc.expected
test/qa_data_sink.cpp
test/qa_dynamic_node.cpp
test/qa_hier_node.cpp
test/qa_scheduler.cpp
test/qa_settings.cpp
test/qa_tags.cpp

* added fmt definition for Annotated<>
* added implicit conversion operator from/to std::string for Annotated
* properties that cannot be matched to fields (settings().set(..)) end up in the node's meta_information map
* to note: `using property_map = std::map<std::string, pmtv::pmt, detail::transparent_less>;` changed to `pmtv::map_t` (needs follow-up in pmt w.r.t. key comparator)
* `node::meta_information` now stores the field/property annotation meta info (e.g. usable in UI) such as 
* `<field_name>::description`, 
* `<field_name>::documentation`,
* `<field_name>::unit`,
* `<field_name>::visible`, and 
* other future annotation meta info.
* changed  `_node->init(/* old settings */ oldSettings, /* new settings */ staged);` to `_node->settings_changed(/* old settings */ oldSettings, /* …

refactored node name, meta_info as reflectable properties

---

bench/bm_case1.cpp
bench/bm_filter.cpp
bench/bm_test_helper.hpp
include/data_sink.hpp
include/graph.hpp
include/node.hpp
include/scheduler.hpp
test/app_plugins_test.cpp
test/blocklib/core/unit-test/common_nodes.hpp
test/blocklib/core/unit-test/tag_monitors.hpp
test/plugins/good_base_plugin.cpp
test/qa_dynamic_node.cpp
test/qa_dynamic_port.cpp
test/qa_hier_node.cpp
test/qa_plugins_test.cpp
test/qa_scheduler.cpp

...  to `{requested, performed, status} work(std::size requested) {..}`
This is preparatory to support:
* limit amount of work to be processed based on explicit scheduler constraints, i.e.
* optimise for latency
* optimise for throughput
* optimise for actual processing time (i.e. if '1k work' takes n-ms, then schedule next time 10k to minimise work overhead or vice verse)
* transparent blocking IO calls: of `BlockingIO` is declared node-implicitly runs internal work function on independent io thread (injected by graph/scheduler tbd.) -- separation between public and internal work function required for decoupling.
N.B. for non-blocking blocks nothing changes compared to before.

changed node:work() signature

---

CMakeLists.txt
bench/bm_case1.cpp
cmake/CompilerWarnings.cmake
include/circular_buffer.hpp
include/node.hpp
include/node_traits.hpp
include/typelist.hpp
include/utils.hpp
src/main.cpp
test/blocklib/core/unit-test/tag_monitors.hpp
test/qa_tags.cpp

For a detailed list of changes look at the commit messages.
Please review *naming*. Do you have ideas for better names?
Example: `Node::work_internal` calls `Node::invoke_process_one` / `Node::invoke_prcess_one_simd`. The latter calls `Derived::process_one_simd` for source nods (unconditionally with offset), otherwise `Node::invoke_process_one`. `Node::invoke_process_one` calls non-member `invoke_process_one_with_or_without_offset`, which in turn calls `Derived::process_one` (with or without offset argument, depending on `can_process_one_with_offset`).
For merged nodes the call stack is deeper still. (If this - for whatever reason - doesn't get `inline`d it's going to be expensive. I feel bad about omitting `always_inline`.)

Extend process_one with optional offset parameter and allow process_bulk to publish less samples in an output

---

include/node.hpp

Span size is 1 and index must always be 0.

Bug fixing in node::forward_tags method.

---

.github/workflows/ci-meson.yml
.github/workflows/ci.yml

Since the last ubuntu22.04 runner image [release](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230724.1), installation of clang from the llvm mirros fails:
https://github.com/fair-acc/graph-prototype/actions/runs/5708009811/job/15465254832#step:5:121
```
$ sudo apt install -y clang-15 libc++-15-dev libc++abi-15-dev
The following packages have unmet dependencies:
libc++1-14 : Conflicts: libc++-x.y
libc++1-15 : Conflicts: libc++-x.y
libc++abi1-14 : Conflicts: libc++abi-x.y
libc++abi1-15 : Conflicts: libc++abi-x.y
libunwind-14 : Conflicts: libunwind-x.y
libunwind-14-dev : Conflicts: libunwind-x.y-dev
Breaks: libunwind-dev
libunwind-15 : Conflicts: libunwind-x.y
libunwind-15-dev : Conflicts: libunwind-x.y-dev
E: Error, pkgProblemResolver::Resolve generated breaks, this …
```

CI: fix clang dependency conflicts by updating the installed clang14 package

---

include/annotated.hpp
include/node.hpp
test/grc/test.grc.expected
test/qa_node.cpp

Few details on implementation:
1) If `stride == 0` then it is not used and `n_samples_to_consume == n_samples_to_process`. 
2) If `stride != 0 and stride < in_available_samples` then `n_samples_to_consume == stride`. 
3) If `stride != 0 and stride > in_available_samples` then samples are consumed till `stride_consumed_counter == stride`. 
Depending on the parameters like `numerator`, `denominator` and available samples. `n_samples_to_process` can change for each `work` function execution, but `stride` is always the same. It can lead to different sample rates over time. In many cases this is normal behavior. If it is not the case then it is  user responsibility to set proper parameters .
It also can happen that `n_required_samples >= stride` but actual `n_samples_to_process < stride` …

Add stride implementation for the node class.

---

include/node.hpp
test/CMakeLists.txt
test/blocklib/core/sources/clock_source.hpp
test/plugins/CMakeLists.txt
test/qa_fft.cpp
test/qa_node.cpp

temporarily disable asan for test which fails due to changes in the github action environment.
runner release that probably caused the failures: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230814.1
Only  mentioned related change is a micro version in cmake.
Also resolves all gcc warnings.

cmake: disable asan for qa_plugin_test

---

include/CMakeLists.txt

Make sure the generated export header is found when building the plugin tests. Seen when using this repo via FetchContent_Declare().

Fix plugin test build

---

include/dataset.hpp
include/port.hpp
test/qa_fft.cpp

This PR includes following changes:
- Add DataSet<float> and Dataset<double> to port suppurted types.
- Add FFT test with flow graph.
- Remove constexpr for port::pmt_type() and dynamic_port::pmt_type() functions when using emscripten. 
**Note!** Last item has to be revisited later! `constexpr` was removed because `emscripten` does not support `constexpr` function for non literal type, like `DataSet<T>`. For the moment after the discussion with @wirew0rm, this solution was considered as a best/easiest which should not even harm the performance. We still need to discuss this problem later especially considering performance issues if any, and the fact that `DataSet` will be used more and more in many other blocks.

Add DataSet<float> and Dataset<double> to port suppurted types.

---

CMakeLists.txt
bench/bm_fft.cpp
test/blocklib/core/fft/fft.hpp
test/blocklib/core/fft/window.hpp
test/qa_fft.cpp
test/qa_node.cpp

This PR includes the following changes:
* Implement window (apodization) function.
* Meta information for DataSet.
* unique_ptr for in_data, out_data and plan.
* Compute ranges as part of copying to DataSet.
* Add integral type to FFT tests.
* fftw wisdom import/export via string.
* Additional unit tests.
* General improvements and bug fixing.
* Change code style according to opendigitizer style guide.
- `enum class window_function : int {...}` includes all supported window types.
- `window` type is declared as `int` in `fft` class to make it available to change it via settings mechanism.
- where it is needed `static_cast` is used to convert between `int` and `window_function` and vice versa.
- @mattkretz suggested another possible solution:
```cpp
struct EnumLike
{
int value;
template …
```

Several changes in FFT

---

include/node.hpp
include/settings.hpp
include/tag.hpp
test/qa_settings.cpp

Based on a suggestion/request by @Jsallay added functionality to reset to and store default block parameter. 
The initial defaults are those settings during block initialisation, including the (optional) parameters that have been passed as constructor arguments, e.g. 
```cpp 
auto &block = flow_graph.make_node<TestBlock<float>>({ { "name", "TestName" }, { "scaling_factor", 2.f } });
```
The reset and store can be triggered via streaming tags `gr:reset_default` and ``gr:store_default` (N.B. naming open for change), or explicitly via the setting accessor methods:
```cpp
block.settings().store_defaults();
// ...
block.settings().reset_defaults();
// reverting to old settings
// block.reset() is optionally called
```
Refactored, introduced some concepts for the optional `settings_changed()` …

added store/reset default block setting functionality

---

include/annotated.hpp
include/node.hpp
include/settings.hpp
test/grc/test.grc.expected
test/qa_settings.cpp

This PR enhances the functionality of the `Annotated<...>` type by introducing range limits and generic validation checks. These are made possible via the optional `Limits<Min, Max, OptValidatorFunc>` type, where the minimum, maximum, and validator are specified as Non-Type Template Parameters (NTTPs).
Here's how you can utilize the new feature:
1. **Basic Limit Specification**:
```cpp
Annotated<float, "sample rate", Limits<int64_t(0), std::numeric_limits<int64_t>::max()>> sample_rate = 1000.0f;
```
2. **Using a Separate Validator Function**:
```cpp
constexpr auto isPowerOfTwo = [](const int &val) { return val > 0 && (val & (val - 1)) == 0; };
Annotated<int, "power of two", Limits<0, 0, isPowerOfTwo>> needPowerOfTwo = 2;
```
N.B. `MIN==MAX` disable the range check leaving the optional …

Enhance `Annotated<...>` with Range Limits and Generic Validation via `Limits<Min, Max, OptValidatorFunc>`

---

bench/bm_case1.cpp
bench/bm_scheduler.cpp
bench/bm_test_helper.hpp
include/README.md
include/data_sink.hpp
include/graph.hpp
include/node.hpp
include/port.hpp
include/port_traits.hpp
include/typelist.hpp
include/utils.hpp
src/main.cpp
test/blocklib/core/fft/fft.hpp
test/blocklib/core/filter/time_domain_filter.hpp
test/blocklib/core/sources/clock_source.hpp
test/blocklib/core/unit-test/common_nodes.hpp
test/blocklib/core/unit-test/tag_monitors.hpp
test/plugins/good_base_plugin.cpp
test/plugins/good_conversion_plugin.cpp
test/plugins/good_math_plugin.cpp
test/qa_data_sink.cpp
test/qa_dynamic_node.cpp
test/qa_dynamic_port.cpp
test/qa_fft.cpp
test/qa_hier_node.cpp
test/qa_node.cpp
test/qa_plugins_test.cpp
test/qa_scheduler.cpp
test/qa_settings.cpp

... as outlined by GR Architecture WG and https://github.com/fair-acc/graph-prototype/issues/148
tackled items:
* refactored port structure (mandatory enum NTTPs vs. optional type-wrapped arguments)
```cpp
class template<typename T, fixed_string PortName, port_type_t PortType, port_direction_t PortDirection, 
typename...  Arguments>
struct Port { /* ... */ };
```
* added optional domain argument
* added default init value (needed for cyclic graphs)
* add isOptional() annotation
* fixed repeated_port name -> name0, name1, name2, ...
* fixed `0 -> 1` for the required min port samples in various tests & code examples (now ensured via a `static_assert(..)`)
* added 'Async' port annotation and 'isSynchronous()' function
* renamed IN,OUT,... short-hand aliases to more explicit/hopefully …

refactored port<T> interface

---

CMakeLists.txt
bench/CMakeLists.txt
bench/bm_fft.cpp
test/CMakeLists.txt
test/blocklib/algorithm/CMakeLists.txt
test/blocklib/algorithm/include/algorithm/fft/fft.hpp
test/blocklib/algorithm/include/algorithm/fft/fft_common.hpp
test/blocklib/algorithm/include/algorithm/fft/fft_types.hpp
test/blocklib/algorithm/include/algorithm/fft/fftw.hpp
test/blocklib/algorithm/include/algorithm/fft/window.hpp
test/blocklib/core/fft/fft.hpp
test/qa_fft.cpp

This PR contains the following changes:
* Implementation of the iterative radix-2 FFT algorithm using bit-reversal permutation.
* FFT block contains 2 template parameters: data type and algorithm type.
* Add test of different FFT algorithms.
* Use `process_bulk` instead of `process_one`
* Allow user to set also output type
* Add additional meta information to the output `dataset`
```text
┌────────────benchmark:─────────────┬──────┬──#N──┬─CTX-SW─┬───CPU cache misses────┬───CPU branch misses───┬─<CPU-I>─┬──min───┬──mean──┬─stddev─┬─median─┬──max───┬─total time─┬─ops/s─┐
│ std::complex<float> - fftw        │ PASS │ 100  │     0  │  29.6k / 179k = 16.5% │  6.76k / 355k =  1.9% │   92.1k │   6 us │  10 us │  37 us │   6 us │ 380 us │       1 ms │ 98.3k │
│ std::complex<float> - fft         │ …
```

FFT implementaion

---

test/CMakeLists.txt

Fix test fails. It seems that `-fsanitize=address` flag causes that too many locals are created. 
For the moment just do not use `-fsanitize=address` flag for emscriptem.

Fix test fails, switch off fsanitize=address for emscriptem.

---

bench/bm_fft.cpp
test/blocklib/algorithm/include/algorithm/fft/window.hpp
test/blocklib/core/fft/fft.hpp
test/qa_fft.cpp

* reduced the API towards a more clean and lean implementation
- reduced 'using' declarations
- removed redundant functions in the block implementation
* changed fftSize from problematic/non-portable `std::size_t` to `std::uint32_t`
* fixed sample_rate, and signal_... names to follow the tag::DEFAULT_TAGS conventions
* added Kaiser window function (pre-requisite for FIR filter calculations)
* updated block documentation
Future Todos:
* semi-private caching vectors (need to be public for unit-test) should be moved to FFT implementations, notably casting from T -> U::value_type should be done there
* use of SIMD primitives where possible
* change window function from int to std::string (parsing + default fall back) function

updated FFT block and helper functions

---

test/blocklib/algorithm/include/algorithm/fft/window.hpp
test/blocklib/core/fft/fft.hpp
test/qa_fft.cpp

... and corresponding unit-tests. This is necessary as we cannot safely transmit C++ enum values across different domains, platforms and languages (e.g. C++, Python, or Java)

added window function to_string & parse API

---

.github/workflows/ci-meson.yml
.github/workflows/ci.yml
sonar-project.properties

- add clang17
- also run on prs not targeted at main
- small cleanups
- emscripten: change from difficult to maintain hash (was a workaround to use the system nodejs) to proper releases
Updating emscripten from 3.1.43 (07/2023) to the latest release 3.1.46 (09/2023) yields compilation errors: https://github.com/fair-acc/graph-prototype/actions/runs/6454443002/job/17520001932 to be investigated

CI: modernize compiler selection and cleanup workflow

---

CMakeLists.txt
sonar-project.properties

Define coverage paths s.t. tests and benchmarks are not counted towards general coverage and line counts, but still analyzed in the test scope. see: https://docs.sonarcloud.io/advanced-setup/analysis-scope/

CI: configure sonarclound coverage paths

---

blocks/basic/include/gnuradio-4.0/basic/common_blocks.hpp
blocks/basic/test/qa_selector.cpp
blocks/fourier/test/qa_fourier.cpp
core/benchmarks/bm_filter.cpp
core/benchmarks/bm_node_api.cpp
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/BlockTraits.hpp
core/include/gnuradio-4.0/Graph.hpp
core/include/gnuradio-4.0/Graph_yaml_importer.hpp
core/include/gnuradio-4.0/Port.hpp
core/include/gnuradio-4.0/Scheduler.hpp
core/test/CMakeLists.txt
core/test/app_grc.cpp
core/test/app_plugins_test.cpp
core/test/qa_Block.cpp
core/test/qa_DynamicBlock.cpp
core/test/qa_HierBlock.cpp
core/test/qa_Scheduler.cpp
core/test/qa_plugins_test.cpp
core/test/qa_port_array.cpp
meta/include/gnuradio-4.0/meta/typelist.hpp
meta/include/gnuradio-4.0/meta/utils.hpp

- Removed the connect syntax with pointers to members
- Added the support for vectors and arrays of ports to the static connect syntax
- Exposing static port names to dynamic ports
- Added syntax for dynamic_connect that works with port names, with the support for port collections

Updated syntax for connections, for ports in collections as well

---

CMakeLists.txt

* Since we have -Og, -O0 (the default) is never a good idea.
* Building the project without a build type (the cmake default) is "usually not desirable" (cmake docs), therefore default to Release with assertions enabled.
* Document build types.
* Warn if the user somehow managed to build without optimization.

CMake: Improve build type defaults

---

.github/workflows/ci.yml

Should handle the warning on the sonar-scanner github action.
See: https://community.sonarsource.com/t/java-11-is-deprecated-as-a-runtime-env-to-scan-your-projects/96597/11

CI: upgrade sonar-scanner action

---

core/include/gnuradio-4.0/Graph.hpp
core/include/gnuradio-4.0/Graph_yaml_importer.hpp
core/test/app_grc.cpp
core/test/app_plugins_test.cpp
core/test/qa_plugins_test.cpp

Make sure we can load/save connections involving port collections, i.e. serialize a connection from block1, port collection 0, sub-index 1 to block2, port collection 0, sub-index 2 as
```
connections:
- [block1, [0, 1], block2, [0, 2]]
```

Support port collections in GRC YAML   

---

.clang-format

A column limit of 0 means that there is no column limit. In this case, clang-format will respect the input’s line breaking decisions within statements unless they contradict other rules.
Thus, clang-format will not make lines longer when the developer decided that shorter is better.
Aligning across lines makes it impossible to stop crazy alignments
without turning off clang-format altogether.

Adjust .clang-format as discussed (too long ago)

---

.github/workflows/ci.yml
CMakeLists.txt
algorithm/CMakeLists.txt
algorithm/include/gnuradio-4.0/algorithm/ImChart.hpp
algorithm/include/gnuradio-4.0/algorithm/fourier/window.hpp
algorithm/test/qa_algorithm_fourier.cpp
blocks/fourier/include/gnuradio-4.0/fourier/fft.hpp
blocks/fourier/test/qa_fourier.cpp
core/CMakeLists.txt
core/src/CMakeLists.txt
sonar-project.properties
third_party/download_external_deps.sh
third_party/magic_enum/magic_enum.hpp
third_party/magic_enum/magic_enum_all.hpp
third_party/magic_enum/magic_enum_containers.hpp
third_party/magic_enum/magic_enum_flags.hpp
third_party/magic_enum/magic_enum_format.hpp
third_party/magic_enum/magic_enum_fuse.hpp
third_party/magic_enum/magic_enum_iostream.hpp
third_party/magic_enum/magic_enum_switch.hpp
third_party/magic_enum/magic_enum_utility.hpp
third_party/refl-cpp/refl.hpp

Presently only 'refl-cpp' and 'magic_enum' -- both expected to be replaced by C++26, for details see: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2996r0.html
Compiler warnings for these external dependencies are enabled by default but can be disabled by the `-DDISABLE_EXTERNAL_DEPS_WARNINGS=ON` cmake flag.
Replaced some custom [from, to] string<->enum by magic_enum ... more to follow. 
This PR focuses more on the CI, build mechanics, and coverage/sonar-line disabling for the inlined header-only libraries.

Inline header only dependencies

---

blocks/basic/include/gnuradio-4.0/basic/DataSink.hpp
blocks/basic/test/qa_DataSink.cpp

Make sure the "finished" flag in the poller is set to true if the poller was created after stop().

DataSink: Do not hand out unfinished pollers after stop()

---

algorithm/include/gnuradio-4.0/algorithm/filter/FilterTool.hpp
algorithm/include/gnuradio-4.0/algorithm/fourier/window.hpp
algorithm/test/CMakeLists.txt
algorithm/test/qa_FilterTool.cpp
algorithm/test/qa_algorithm_fourier.cpp
blocks/basic/include/gnuradio-4.0/basic/DataSink.hpp
blocks/filter/include/gnuradio-4.0/filter/time_domain_filter.hpp
core/include/gnuradio-4.0/HistoryBuffer.hpp
core/test/qa_Settings.cpp
core/test/qa_buffer.cpp
meta/include/gnuradio-4.0/meta/formatter.hpp
meta/test/CMakeLists.txt
meta/test/qa_formatter.cpp

This PR introduces implementation for both Infinite Impulse Response (IIR) and Finite Impulse Response (FIR) filters within the `gr::filter` namespace. 
The primary focus lies in:
* Provide a robust, clean, and lean C++-only implementation (<800 SLOCs!) that is easy(/ier) to maintain and can be used within `Block<T>`s to derive default FIR or IIR filter parameters based on high-level filter parameter requirements w/o strings attached (e.g. needing Python to compute multiplications of complex numbers).
* consistent evaluation and creation of the required IIR and FIR filter coefficients, e.g.
```cpp
constexpr auto kFilterParams = FilterParameters{ .order = 4UZ, .fLow = 4.0, .fHigh = 6.0, .attenuationDb = 60, .fs = 1000.0 }
const auto digitalBandPass1 = iir::designFilter<double>(BANDPASS, …
```

IIR and FIR coefficient generator and time-domain filter (<800 SLOCs!)

---

core/include/gnuradio-4.0/HistoryBuffer.hpp
core/test/qa_buffer.cpp

... and filled some minor loop-holes in unit-tests (coverage)

added HistoryBuffer::reset(<default>)

---

algorithm/include/gnuradio-4.0/algorithm/filter/FilterTool.hpp
algorithm/test/qa_FilterTool.cpp
meta/include/gnuradio-4.0/meta/UncertainValue.hpp
meta/test/qa_UncertainValue.cpp

This includes the computation of the propagation of uncertainty according to:
$$ \sigma_y^2[0] = \sum_{i=0}^{M} b^2[i]·σ_x^2[i] + \sum_{j=1}^{N} \sum_{k=1}^{N} a[j]·a[k]·R_{yy}[|j-k|]·σ_y[j]·σ_y[k] $$
with $R_{yy}[distance]$ being the auto-correlation function of the impulse response as an estimate of the covariance matrix.
```cpp
Filter<UncertainValue<double>> myFilter(filterSections);
UncertainValue<double> outputSample = myFilter.processOne({inputSample, noise});
double mean   = gr::value(outputSample);
double stddev = gr::uncertainty(outputSample);
```
The more pronounced linear group-delay for the FIR is normal due to the usually larger filter kernel. N.B. the IIR filter has about a 50% poorer noise/uncertainty suppression which is also linked to the FIR filter kernel size rather …

Integrate UncertainValue to IIR and FIR filter

---

blocks/basic/include/gnuradio-4.0/basic/common_blocks.hpp
core/include/gnuradio-4.0/Port.hpp
core/test/qa_DynamicBlock.cpp

This PR is split into three semantically distinct commits:
- Convert qa_DynamicBlock to a real boost ut test
- Add a test for dynamically reallocating the ports collection
- Fix reallocating Port instances
The final commit is the patch with the actual fix, the move constructor of `Port` was missing some fields, which caused connections to break as soon as a Port was relocated.
This already fixes https://github.com/fair-acc/opendigitizer/issues/90.
However, there is more to the relationship between `DynamicPort` and its `Port` counterpart. Since they are so tightly coupled together, moving a Port needs to modify the accessor in `DynamicPort`. This is not needed in the above unit test, because the `DynamicPort`s [are always recreated](https://github.com/fair-acc/graph-prototype/blob/427aea10 …

Fix relocating Port instances

---

core/benchmarks/bm_Buffer.cpp

Benchmarks on AMD Ryzen 9 5900X:
**GCC 13.2.1**
```text
all micro-benchmarks passed:
┌─────────────────────────benchmark:─────────────────────────┬──────┬─#N─┬─CTX-SW─┬───CPU cache misses────┬───CPU branch misses───┬─<CPU-I>─┬──min───┬──mean──┬─stddev─┬─median─┬──max───┬─total time─┬─ops/s─┐
│    POSIX: 1 producers -< 1  >-> 1 consumers                │ PASS │ 8  │     8  │ 9.08k / 19.8k = 45.8% │ 5.48k / 37.3k = 14.7% │    1.9m │ 158 ms │ 160 ms │   1 ms │ 160 ms │ 162 ms │       1  s │ 62.5M │
│    POSIX: 1 producers -< 1  >-> 2 consumers                │ PASS │ 8  │     8  │ 3.18k / 13.9k = 23.0% │ 5.04k / 36.6k = 13.8% │    1.9m │ 253 ms │ 274 ms │  13 ms │ 282 ms │ 287 ms │       2  s │ 36.6M │
│    POSIX: 1 producers -< 1  >-> 4 consumers                │ PASS │ 8  │     8  │ 3.13k …
```

re-enable POSIX buffer benchmarks

---

core/include/gnuradio-4.0/Settings.hpp
core/include/gnuradio-4.0/Tag.hpp
core/include/gnuradio-4.0/reflection.hpp
core/test/qa_DynamicPort.cpp
core/test/qa_Tags.cpp
meta/include/gnuradio-4.0/meta/utils.hpp

`pmtv::map_t` got a transparent comparator that `std::map<std::string, pmt_t, std::less<>>` required:
* explicit comparators for fixed_string
* DefaultTag
added corresponding unit-tests, removed now obsolete code, and added implicit equivalency for DefaultTag names such as `"XXX"` "and `"gr:XXX"`. N.B. the later is required for compatibility with SigMF.

pmtv:map_t std::less<> follow-up update

---

core/include/gnuradio-4.0/Scheduler.hpp

Make sure a started scheduler can be stopped afterwards, by setting the expected RUNNING state.
Part of issue #217.

Scheduler: Set running state for multithreaded schedulers

---

.github/workflows/single-header.yml
README.md
devtools/singleheader-config-graph.json

This PR updates the single header generator configuration to adapt to the updated Header filenames and changed dependencies.
Also updates the readme with a new compiler explorer sample.
For this to be useful with compiler-explorer we'll have to look into compile times, the "sample" I added now is barely doing anything and still only compiles without timeout on `-O2`.

CI: adopt singleheader CI to updated filenames

---

core/include/gnuradio-4.0/Settings.hpp
core/include/gnuradio-4.0/Transactions.hpp
core/test/grc/test.grc.expected
core/test/qa_Settings.cpp
meta/include/gnuradio-4.0/meta/formatter.hpp
meta/test/qa_UncertainValue.cpp
meta/test/qa_formatter.cpp

This PR includes the following changes:
- Add `property_map` as supported type to Settings and Transactions.
- Add `fmt::formatter` for `property_map`

Add `property_map` as supported type to Settings and Transactions.

---

blocks/basic/include/gnuradio-4.0/basic/FunctionGenerator.hpp
blocks/basic/include/gnuradio-4.0/basic/SignalGenerator.hpp
blocks/basic/include/gnuradio-4.0/basic/clock_source.hpp
blocks/basic/test/qa_sources.cpp
core/include/gnuradio-4.0/Tag.hpp

The `FunctionGenerator` class generates a variety of functions and their combinations.
It supports multiple function types, including Constant, Linear Ramp, Parabolic Ramp, Cubic Spline, and Impulse Response.
Each function type is configurable with specific parameters, enabling precise tailoring to meet the user's requirements.
Users can create sequences of various functions using tags.
Some helper methods to create tags or property maps are provided: 1) `create{FunctionName}Tag(...)`, 2) `create{FunctionName}PropertyMap(...)`
Supported function types and their configurable parameters:
* Const
- Constantly returns the same value, specified by 'startValue'.
To generate a tag use `createConstTag(tagIndex, startValue)`.
* LinearRamp
- Interpolates linearly between a start and a final value …

Implementation of FunctionGenerator class

---

algorithm/include/gnuradio-4.0/algorithm/ImChart.hpp
blocks/basic/include/gnuradio-4.0/basic/clock_source.hpp
blocks/testing/CMakeLists.txt
blocks/testing/include/gnuradio-4.0/testing/ImChartMonitor.hpp
blocks/testing/test/CMakeLists.txt
blocks/testing/test/qa_UI_Integration.cpp
core/include/gnuradio-4.0/HistoryBuffer.hpp

Added a small example/demo how UI widgets could be integrated using the existing GR `Block<T>` definitions and buffer handling. The key is that the blocks have the `BlockingIO<false>` attribute so that the `invokeWork()` function (and in turn the `process[One, Bulk](...)`) are called from within the UI thread. 
Abbreviated example (full on is < 100 SLOCs):
```cpp
template<typename T>
struct ImChartMonitor : public Block<ImChartMonitor<T>, BlockingIO<false>> {
PortIn<T>   in;
// [...]
HistoryBuffer<T>   _historyBufferX{ 1000 };
HistoryBuffer<T>   _historyBufferY{ 1000 };
HistoryBuffer<Tag> _historyBufferTags{ 1000 };
// [...]
constexpr void
processOne(const T &input) noexcept {
in.max_samples = 2 * sample_rate / 25; // poor man's rate limiter to avoid loosing/overriding samples when the UI …
```

UI integration tests/demo

---

core/include/gnuradio-4.0/Block.hpp
core/test/qa_Block.cpp

Include `Async` ports to the calculation of `nSamplesToNextTag`, `nSamplesToNextTagAfter`, `nSamplesToEosTag`.
It fixes he problem when all input ports are Async and did't receive tags or pending tags in Async ports.

Include Async ports to the calculation of nSamplesToTag.

---

core/include/gnuradio-4.0/Scheduler.hpp

Makes it possible to check whether the scheduler finished, without blocking.

Scheduler: add function to test whether a MT scheduler is still running

---

blocks/basic/include/gnuradio-4.0/basic/common_blocks.hpp
blocks/testing/include/gnuradio-4.0/testing/FunctionBlocks.hpp
core/benchmarks/bm_Buffer.cpp
core/benchmarks/bm_HistoryBuffer.cpp
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/BlockTraits.hpp
core/include/gnuradio-4.0/Buffer.hpp
core/include/gnuradio-4.0/CircularBuffer.hpp
core/include/gnuradio-4.0/Port.hpp
core/include/gnuradio-4.0/Profiler.hpp
core/test/qa_Messages.cpp
core/test/qa_buffer.cpp
core/test/qa_port_array.cpp

In this PR new `ConsumableInputRange` for inputs instead of pure `std::span` is implemented. 
Followup issue https://github.com/fair-acc/graph-prototype/issues/258

Add ConsumableInputRange for inputs instead of pure std::span.

---

core/include/gnuradio-4.0/Scheduler.hpp

This commit fixes runaway spamming of messages as soon as one is sent to/from the scheduler.

Fix runaway multiplication of messages

---

.github/workflows/ci-meson.yml
.github/workflows/ci.yml
.github/workflows/single-header.yml
CMakeLists.txt
algorithm/test/qa_algorithm_fourier.cpp
blocks/basic/include/gnuradio-4.0/basic/Selector.hpp
blocks/basic/include/gnuradio-4.0/basic/clock_source.hpp
blocks/basic/test/qa_DataSink.cpp
blocks/basic/test/qa_Selector.cpp
blocks/basic/test/qa_sources.cpp
blocks/fourier/include/gnuradio-4.0/fourier/fft.hpp
blocks/fourier/test/qa_fourier.cpp
blocks/testing/include/gnuradio-4.0/testing/TagMonitors.hpp
core/benchmarks/bm_Buffer.cpp
core/benchmarks/bm_fft.cpp
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/CircularBuffer.hpp
core/include/gnuradio-4.0/Graph.hpp
core/include/gnuradio-4.0/Scheduler.hpp
core/include/gnuradio-4.0/Settings.hpp
core/include/gnuradio-4.0/Transactions.hpp
core/include/gnuradio-4.0/annotated.hpp
core/test/qa_Block.cpp
core/test/qa_Settings.cpp
core/test/qa_Tags.cpp
core/test/qa_grc.cpp
core/test/qa_port_array.cpp
meta/include/gnuradio-4.0/meta/utils.hpp

This PR addresses issue https://github.com/fair-acc/graph-prototype/issues/229
While there are compile-time concepts that check the correct signature, these checks are being implemented/tested during runtime and thrown during `Block<T>` construction to provide some more user-palatable warning messages and first-order remedies.
1. clean-up qa_Block
* replace custom CountSource with TagSource
* replace direct block settings access with Block(initialiser list)
2. added checkBlockContracts<TBlock>() checker
Block<T>() default constructor checks, throws, and provides first-order remedies for:
* unsupported settings type
* missing or wrong process[One, Bulk] signatures
* added deprecation warning if raw `work(...)` is being implemented
* added unit-tests to specifically test the settings and …

Implement C++20 Concept to ensure work(std::size_t) function signature in Block classes

---

core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/BlockTraits.hpp
core/include/gnuradio-4.0/CircularBuffer.hpp
core/test/qa_Block.cpp

These 2 signatures are now supported:
```cpp
gr::work::Status
processBulk(gr::ConsumableSpan auto, std::span<T>)
requires(processVariant == ProcessBulkVariant::CONSUMABLE_SPAN)
{
// do some bulk-type processing
return gr::work::Status::OK;
}
gr::work::Status
processBulk(gr::ConsumableSpan auto &, std::span<T>)
requires(processVariant == ProcessBulkVariant::CONSUMABLE_SPAN2)
{
// do some bulk-type processing
return gr::work::Status::OK;
}
```
The support for arrays will be added separately, as it requires extensive changes throughout the code.
To the reviewer, please carefully review the changes in `concept processBulk_requires_ith_output_as_span` within the `BlockTraits.hpp` file. I believe there may be a redundant check.

Add possibility to use ConsumableSpan in processBulk signature.

---

core/include/gnuradio-4.0/CircularBuffer.hpp
core/include/gnuradio-4.0/ClaimStrategy.hpp
core/test/qa_buffer.cpp

Fix race condition in multi-producer CircularBuffer
In MultithreadedStrategy, the _cursor is pushed by the writers on reserve, i.e. points to the next's write's start position. Do not use by the readers to determine the number slots available for reading, but track that as a separate readCursor.
To update the readCursor safely when publishing a range, let a writer wait for any previous ranges to be published first. This trades correctness and simpler implementation for some performance.
These issues somehow surface with T=std::map (gr::Message), so add tests for that.

Fix race condition in multi-producer CircularBuffer

---

.github/workflows/ci.yml
.gitignore
CMakeLists.txt
blocks/CMakeLists.txt
blocks/basic/include/gnuradio-4.0/basic/common_blocks.hpp
blocks/http/CMakeLists.txt
blocks/http/include/gnuradio-4.0/http/HttpBlock.hpp
blocks/http/test/CMakeLists.txt
blocks/http/test/pre.js
blocks/http/test/qa_HttpBlock.cpp
blocks/testing/include/gnuradio-4.0/testing/FunctionBlocks.hpp
core/include/gnuradio-4.0/Port.hpp
core/test/qa_DynamicBlock.cpp

This implements the `HttpBlock` as described in #236.
The WebAssembly implementation took quite some jumping through hoops to get right.
There are a lot of quirks with regard to threading in emscripten, that make the implementation a minefield of risking getting stuck in infinite loops, because the emscripten thread for various reasons is unable to make any progress.
Unfortunately we cannot use `ASYNCIFY`, because that is incompatible with exceptions support ([that are already enabled](https://github.com/fair-acc/graph-prototype/blob/530ce6298a6138140de5ac6e05eae95703cdc47f/CMakeLists.txt#L84)).
There is also this fun [emscripten regression](https://github.com/emscripten-core/emscripten/issues/8234#issuecomment-1333548834), which means it's currently impossible to cancel asynchronously …

Implement HttpBlock

---

blocks/basic/include/gnuradio-4.0/basic/DataSink.hpp
blocks/basic/include/gnuradio-4.0/basic/Selector.hpp
blocks/basic/test/qa_Selector.cpp
core/benchmarks/bm_Buffer.cpp
core/benchmarks/bm_HistoryBuffer.cpp
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/Buffer.hpp
core/include/gnuradio-4.0/BufferSkeleton.hpp
core/include/gnuradio-4.0/CircularBuffer.hpp
core/include/gnuradio-4.0/Port.hpp
core/include/gnuradio-4.0/Profiler.hpp
core/test/plugins/good_base_plugin.cpp
core/test/qa_Block.cpp
core/test/qa_DynamicBlock.cpp
core/test/qa_DynamicPort.cpp
core/test/qa_HierBlock.cpp
core/test/qa_buffer.cpp
core/test/qa_port_array.cpp

Here are also some comments on this PR. Probably they should be move to the documentation:
1) The method `BufferReader::get() `can be called multiple times without the need to invoke `consume()` in between.
2) The `consume()` method can only be invoked once. Calling it a second time consecutively triggers `std::abort`, causing the program to terminate.
3) Instead of directly using c`onsume()`, consider using `tryConsume()`, which returns true if the consumption is successful or false if the span has already been consumed.
4) Each `ConsumableInputRange` possesses its own internal `std::span`. This implies that invoking `get()` multiple times results in distinct internal `std::span` objects. This behavior could lead to undefined behavior. For instance, if `ConsumableSpan auto r1 = …

Refactoring of ReserveOutputSpan

---

blocks/basic/include/gnuradio-4.0/basic/common_blocks.hpp
blocks/testing/include/gnuradio-4.0/testing/ImChartMonitor.hpp
blocks/testing/test/qa_UI_Integration.cpp
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/Graph.hpp
core/include/gnuradio-4.0/annotated.hpp
core/test/qa_Block.cpp
core/test/qa_HierBlock.cpp

This adds default `Drawable` annotation in view of issue https://github.com/fair-acc/opendigitizer/issues/131 to declare whether a block supports rendering UI content that -- if declared -- must be drawn/processed through a mandatory `void draw() {...}` function, e.g.: 
```cpp
template<typename T>
struct ImChartMonitor : public Block<ImChartMonitor<T>, BlockingIO<false>, Drawable<UICategory::ChartPane, "console">> {
PortIn<T>   in;
float       sample_rate = 1000.0f;
std::string signal_name = "unknown signal";
constexpr void processOne(const T &input) noexcept { /*  ... as before ... */    }
work::Status draw() noexcept {
[[maybe_unused]] const work::Status status = this->invokeWork(); // calls work(...) -> processOne(...) (all in the same thread as this 'draw()'
// handle drawing code …
```

added Drawable<UICategory, ToolKit> block annotation

---

blocks/testing/include/gnuradio-4.0/testing/TagMonitors.hpp
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/Port.hpp
core/include/gnuradio-4.0/PortTraits.hpp
core/include/gnuradio-4.0/Tag.hpp
core/include/gnuradio-4.0/annotated.hpp
core/test/qa_Block.cpp
core/test/qa_Messages.cpp
core/test/qa_Settings.cpp

This PR aims to restructure the core work function dispatch mechanism implemented in `Block::workInternal`.
Noteworthy changes:
- breaks up the code into determining available samples and afterwards dispatching to the correct work function
- restructure and partially reimplement decimate and stride functionalities:
- the decimation settings (numerator/denominator) now determine the minimum atomic amount of work that can be processed (previously this was determined by the ports' minimum samples)
- stride is applied after denominator samples. (Previously controlled by the ports' maxium samples)
- cleanup
- reduce (gcc) warnings to 0
Open issues:

Refactor workInternal

---

algorithm/include/gnuradio-4.0/algorithm/ImChart.hpp
algorithm/include/gnuradio-4.0/algorithm/fourier/fftw.hpp
bench/benchmark.hpp
blocks/basic/include/gnuradio-4.0/basic/FunctionGenerator.hpp
blocks/basic/include/gnuradio-4.0/basic/Selector.hpp
blocks/basic/include/gnuradio-4.0/basic/common_blocks.hpp
core/benchmarks/bm-nosonar_node_api.cpp
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/BlockTraits.hpp
core/include/gnuradio-4.0/CircularBuffer.hpp
core/include/gnuradio-4.0/Graph_yaml_importer.hpp
core/include/gnuradio-4.0/Port.hpp
core/test/qa_Block.cpp
core/test/qa_buffer.cpp

* hides the internal std::vector/std::array implementation to indicate more clearly to the user that the user code only gets a non-owning reference to the input and output port data. This should make the user API safer and allow changing the internal implementation without breaking the user code.
**Some example usages:**
  * prevents accidentally connecting ports with incompatible sampling rates, quantity- and unit types.
  * used to condition graphs/charts (notably the min/max range),
  * detect saturation/LNA non-linearities,
  * detect computation errors
  * ...
Follows the ISO 80000-1:2022 Quantities and Units conventions:
  * https://www.iso.org/standard/76921.html
  * https://en.wikipedia.org/wiki/ISO/IEC_80000
  * https://blog.ansi.org/iso-80000-1-2022-quantities-and-units/ …

std::span<std::span<...>> & Port<T>: enable std::any & meta-data

---

core/include/gnuradio-4.0/Block.hpp

@frankosterfeld discovered a regression in one of the out of tree blocks in gr-digitizer, reported [here](https://github.com/fair-acc/graph-prototype/pull/297/files#r1542781655).
If the processBulk function does not consume all samples up to the eos tag, the previous code would terminate processing anyway, leading to the unprocessed samples being dropped.
This is becaue the ConsumableSpan does not provide a way to determine how much the processsing function has actually consumed.
This change solves this by only handling explicitly stopped blocks after the block has processed, which leaves the eos tag handling for the start of the next call, where it is sufficient to check if the eos tag is the first sample.
Also fixes a few minor inconsistencies discovered by @frankosterfeld.

Block: fix EoS handling for process bulk not consuming samples

---

blocks/basic/test/qa_DataSink.cpp
blocks/basic/test/qa_sources.cpp
blocks/filter/test/qa_filter.cpp
blocks/fourier/test/qa_fourier.cpp
blocks/http/test/qa_HttpBlock.cpp
blocks/testing/test/qa_UI_Integration.cpp
core/test/qa_Block.cpp
core/test/qa_DynamicPort.cpp
core/test/qa_Messages.cpp
core/test/qa_Scheduler.cpp
core/test/qa_Settings.cpp
core/test/qa_Tags.cpp
core/test/qa_buffer.cpp
core/test/qa_grc.cpp
core/test/qa_plugins_test.cpp
core/test/qa_reader_writer_lock.cpp
core/test/qa_thread_affinity.cpp
core/test/qa_thread_pool.cpp

UT fixed the initialisation of the command line arguments for clang in https://github.com/boost-ext/ut/commit/3cfd9937e1d4c9375f7d7904a5ba6a1926f7161f. This change removes the special case which disables the junit style ut reporter in most unit tests.
For qa_grc there is still a segfault if the junit reporter is enablet but this seems to be a slightly different case. The segfault occurs in the static initialisation of the block registy in gr::registerBlock.

ut: remove clang workaround after upstream fixes

---

core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/Message.hpp
core/include/gnuradio-4.0/Scheduler.hpp
core/test/qa_Messages.cpp

* Make sure clients can subscribe to kLifeCycleState and kStagedSetting
* Make sure messages sent before scheduler initialisation (i.e. before runAndWait()) are not lost. (needed for initial subscriptions, to have the guarantee to receive everything)
* Minor code cleanup (avoid contains()/empty() checks where unnecessary)

Messaging fixes

---

blocks/basic/test/qa_DataSink.cpp
blocks/basic/test/qa_Selector.cpp
blocks/basic/test/qa_sources.cpp
blocks/fourier/test/qa_fourier.cpp
blocks/http/test/qa_HttpBlock.cpp
blocks/testing/test/qa_UI_Integration.cpp
core/benchmarks/bm-nosonar_node_api.cpp
core/benchmarks/bm_Scheduler.cpp
core/test/qa_DynamicBlock.cpp
core/test/qa_DynamicPort.cpp
core/test/qa_Messages.cpp
core/test/qa_Scheduler.cpp
core/test/qa_Tags.cpp
core/test/qa_grc.cpp

Wrapped `schduler.runAndWait()` calls with `expect()`  to ensure return value presence.

Wrapped schduler.runAndWait() calls

---

.github/workflows/ci.yml

Followup/fixup of #309 which broke the build on the main branch.
The docker step for branches needs a git checkout. For PRs this is not needed because the docker step does its own checkout and the path-filter uses the github API for PRs but needs a checkout for 'push' events.

CI: fix docker step for main branch

---

blocks/basic/include/gnuradio-4.0/basic/DataSink.hpp
core/benchmarks/bm-nosonar_node_api.cpp
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/CircularBuffer.hpp
core/include/gnuradio-4.0/Port.hpp
core/include/gnuradio-4.0/Scheduler.hpp
core/test/qa_buffer.cpp

This PR contains the following changes:
* `ConsumableInputRange` counter
* Deferred `consume()`, consume is executed in destructor of the last range using proper `SpanReleasePolicy`
* Default `SpanReleasePolicy` is `ProcessNone`
* `reader.get()` by default returns all available samples
* Multiple consecutive `reader.get()` calls are possible, `nSamples` of the first `get()` call is the max for all subsequent calls.
* Remove `consume()` method from `buffer_reader`, consume is possible only via `ConsumableInputRange.consume()`

ConsumableInputRange and buffer_reader updates:

---

core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/LifeCycle.hpp
core/include/gnuradio-4.0/Scheduler.hpp
meta/include/gnuradio-4.0/meta/utils.hpp
meta/test/qa_traits.cpp

While library internal code should be kept exception free, users (often using other C/C++ libraries) are free to throw exceptions to indicate rare errors. 
These exceptions are internally wrapped and passed up the chain to the graph->scheduler. 
In case the scheduler 'msgOut' is not connected these error messages are in turn converted to exceptions again.

wrap user-defined function exceptions to error messages

---

CMakeLists.txt
blocks/basic/include/gnuradio-4.0/basic/PythonBlock.hpp
blocks/basic/include/gnuradio-4.0/basic/PythonInterpreter.hpp
blocks/basic/test/CMakeLists.txt
blocks/basic/test/qa_PythonBlock.cpp
cmake/CheckNumPy.py
core/include/gnuradio-4.0/Settings.hpp
core/test/CMakeLists.txt

This pull request adds the `PythonBlock` and `PythonInterpreter`, significant new functionalities within GNURadio 4.0 designed to facilitate seamless integration of Python scripts into the C++ framework. 
These modules enable dynamic execution of Python code directly within GNURadio flow-graphs, enhancing the flexibility and capability of signal processing workflows.
1. **PythonBlock**:
- can execute user-defined scripts that process data streams, allowing custom processing logic to be defined at runtime.
- handles setup, execution, and teardown of Python environments, ensuring that Python code can run efficiently alongside C++ operations.
2. **PythonInterpreter**:
- manages Python's initialisation and finalisation, ensuring that the Python runtime is correctly managed across the usage …

new Feature: PythonBlock and PythonInterpreter

---

.restyled.yaml

update restyled to use clang-format 18. Fixed on a specific image so there will be no surprise reformatting if clang-format gets it's next release.
Also disable creating pull requests and instead only push the branch and set the status check to decrease the amount of PRs especially for Draft PRs.
Since clang-format is not yet enabled here, we could also wait with merging this until we have finalized the clang-format rules.
Depends on restyled upstream clang-format support: https://github.com/restyled-io/restylers/pull/735

CI: update restyled to clang-format 18

---

CMakeLists.txt
blocks/basic/test/qa_PythonBlock.cpp
core/include/gnuradio-4.0/Tag.hpp

this is a follow-up of:
* primarily: [Move formatting code to a different header file ...](https://github.com/gnuradio/pmt/pull/111)
* optional 'EMBEDDED' flag that is tied to the 'MinSizeRel' build target to disable/minimise code features for embedded systems (e.g. code-size, console printouts, etc.)
* integration of [Include What You Use](https://github.com/include-what-you-use/include-what-you-use) tool (optional, if available/installed

explicit pmtv formatter header, new EMBEDDED & IWYU integration

---

blocks/basic/test/qa_DataSink.cpp
core/include/gnuradio-4.0/Settings.hpp
core/include/gnuradio-4.0/Transactions.hpp

This PR contains the following changes:
* Bug fix in settings, add `auto_update` parameters outside of `tuple_for_each`
* Refactoring of `CtxSettings` constructor.
* Fix bug in settings `autoUpdate()`
* Use `processMembers()` function

Update Settings and CtxSettings

---

core/include/gnuradio-4.0/Buffer.hpp
core/include/gnuradio-4.0/BufferSkeleton.hpp
core/include/gnuradio-4.0/CircularBuffer.hpp
core/test/qa_buffer.cpp

This PR adds the nSamplesConsumed() and nSamplesPublished() methods to the BufferReader/Writer. 
These methods will help `Block` class to check if tags should be forwarded when asynchronous ports are present.

Add nSamplesConsumed() and nSamplesPublished() to BufferReader/Writer

---

.all-contributorsrc
README.md

Manually adds all contributors which were previously added via the all-contributors app, but where the PRs were not automatically rebased. The README should be updated the next time the app will update any contribution.

doc: manually add contributors [ci skip]

---

CMakeLists.txt
bench/benchmark.hpp
blocks/basic/include/gnuradio-4.0/basic/clock_source.hpp
blocks/basic/include/gnuradio-4.0/basic/common_blocks.hpp
blocks/http/include/gnuradio-4.0/http/HttpBlock.hpp
blocks/testing/include/gnuradio-4.0/testing/NullSources.hpp
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/CircularBuffer.hpp
core/include/gnuradio-4.0/DataSet.hpp
core/include/gnuradio-4.0/Port.hpp
core/include/gnuradio-4.0/Scheduler.hpp
core/test/CMakeLists.txt
core/test/qa_Block.cpp
core/test/qa_DynamicPort.cpp
core/test/qa_Messages.cpp
core/test/qa_Scheduler.cpp
core/test/qa_Settings.cpp
docker/Dockerfile

1. When a block detects that it is no longer required (i.e., it has no downstream consumers), this feature ensures that the block declares itself 'DONE' and severs connections to upstream blocks. This feature is controlled by the Block<T>::disconnect_on_done parameter (default: true)
2. added `buffer().n_writers()` interface tracking the number of writers and when a buffer and/or two or more ports are not connected anymore. Makes the first item simpler/cleaner.
3. added some documented default blocks in-line with GR3: NullSource, NullSink, Copy, HeadBlock, CountingSource, CountingSink -- naming of the 'HeadBlock' -- while ubiquitously used in GR3 -- should be discussed with the architecture team because of semantics.

feature: propagate `DONE` to and disconnect from upstream blocks

---

.github/workflows/ci.yml
CMakeLists.txt
ClangBuildAnalyzer.ini
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/Settings.hpp
core/include/gnuradio-4.0/Tag.hpp
core/include/gnuradio-4.0/Transactions.hpp
core/test/qa_Settings.cpp

* eliminated looping over a tuple and for_each (expensive to instantiate) and to use a straight `std::array<std::string_view, ...> kDefaultTags` instead. The latter can also be evaluated during compile-time.
* added ccache support (can be disabled) which should help for local development that needs to switch between branches.
Comparative timings for the qa_Scheduler unit-tests:
Before (full parallel build):
```text
real    8m43.031s
user    51m13.146s
sys     2m13.891s
```
ClangBuildAnalyzer output for `qa_scheduler` [before](https://github.com/fair-acc/gnuradio4/files/15384756/qa_scheduler_analysis_before.txt)
After:
```text
real    6m52.364s
user    42m5.309s
sys     1m41.661s
```
ClangBuildAnalyzer output for `qa_scheduler`  [after](https://github.com/fair-acc/gnuradio4/files/15384765/q …

compile-time improvements - for_each std::tuple -> std::array

---

core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/Graph_yaml_importer.hpp
core/include/gnuradio-4.0/Settings.hpp
core/include/gnuradio-4.0/Transactions.hpp
core/test/qa_Settings.cpp
core/test/qa_grc.cpp

This PR includes the implementation of `CtxSettings`, which will  replace the existing `BasicSettings`. 
Several tasks need to be addressed following this PR to fully integrate `CtxSettings` into the codebase:
1) Remove Base Settings Class and `BasicSettings`. The old `BasicSettings` and its base class need to be removed to eliminate redundancy and avoid confusion.
2) Eliminate usage of `unique_ptr` for Block::_settings
3) Update function names to clearly indicate they are associated with `CtxSettings`, enhancing code readability.
4) Expand Unit Testing. Add comprehensive unit tests specifically targeting `CtxSettings` .
5)  `using MatchPredicate = std::function<std::optional<bool>(const pmtv::pmt &, const pmtv::pmt &, std::size_t)>;`
replace this with the new matcher structure. See …

Implement CtxSettings, use instead of BasicSettings.

---

blocks/testing/test/qa_UI_Integration.cpp
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/Transactions.hpp

This PR contains implementation of the `AutoUpdatePolicy` when context is not found in stored settings.
Two possible options are available: `AddToStored` and `Ignore`.

Auto update policy when context is not found in stored settings.

---

core/test/qa_plugins_test.cpp

Fix clang-18 compilation error: use std::ranges::find instead of std::ranges::contains.

Fix clang-18 compilation error

---

core/include/gnuradio-4.0/Block.hpp

Reverting to BasicSettings due to performance issues. Investigate the performance problems reported by @daniestevez, and once resolved, switch back to `CtxSettings`.

Back to BasicSettings due to performance issues.

---

blocks/CMakeLists.txt
blocks/fileio/CMakeLists.txt
blocks/fileio/include/gnuradio-4.0/fileio/BasicFileIo.hpp
blocks/fileio/test/CMakeLists.txt
blocks/fileio/test/qa_FileIo.cpp
core/benchmarks/CMakeLists.txt
core/test/CMakeLists.txt

... nomen est omen.
@xaratustrah enjoy!

new block: BasicFile[Sink, Source]

---

blocks/testing/include/gnuradio-4.0/testing/TagMonitors.hpp

Add support to store UncertainValue samples for TagMonitor and TagSink by removing error part.
This is neede for some unit tests.

Add support to store UncertainValue samples for TagMonitor and TagSink 

---

CMakeLists.txt

For implementing std::execution::par, gcc relies on the TBB library. On systems without TBB installed it falls back to the non-parallel implementation, but as soon as the TBB header is available it will try to use it and require linking against TBB.
https://github.com/gcc-mirror/gcc/blob/releases/gcc-14.1.0/libstdc%2B%2B-v3/include/bits/c%2B%2Bconfig#L874-L882 Since TBB is a bigger dependency, making it a required dependency is not an option, so this introduces the option ENABLE_TBB which by default is off but can be used to add the dependency.
The alternative would be to add TBB as a non-required dependency and only add the linker flag if it is found, following the approach from gcc. Would be one less cmake option but I think having it explicit is better allow reproduction between …

Fix optional gcc dependency on TBB

---

core/include/gnuradio-4.0/Block.hpp
core/test/qa_Block.cpp
core/test/qa_Tags.cpp

The PR includes the following changes:
1. Modify `Block` class to manage SyncInput-AsyncOutput ports cases.
2. Add `SyncOrAsync` unit test to cover various scenarios of sync/async input/output ports.
3. Update `qa_Tags `expected values; the default policy now drops epilogue samples.

Change Block to handle SyncInput-AsyncOutput ports case.

---

blocks/fourier/include/gnuradio-4.0/fourier/fft.hpp
blocks/testing/include/gnuradio-4.0/testing/PerformanceMonitor.hpp
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/annotated.hpp
core/test/qa_Block.cpp
core/test/qa_Settings.cpp

Naming is hard... 
In the Block class, we had members `denominator` and `numerator`, which can be confusing due to how they are used. These fields define the resampling ratio as `numerator/denominator`. 
The exact implementation takes `denominator` input samples and creates `numerator` output samples. Meaning that `n_input = k * denominator` and `n_output = k * numerator`. They also act as constraints for the minimum number of input/output samples.
In this PR  `numerator` is renamed to `output_chunk_size` and `denominator` to `input_chunk_size`  which should reflect the purpose of these variables clearly.
In addition documentation was also updated.

Rename numerator to output_chunk_size and denominator to input_chunk_size

---

.github/workflows/ci.yml
cmake/CompilerWarnings.cmake
core/include/gnuradio-4.0/BlockModel.hpp
docker/Dockerfile

* `-Wmissing-field-initializers warning` is a confusing warning which is probably not what most users expect.
For details see: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96868#c3
* added gcc-13 target (backwards compatibility) since gcc-14 isn't as widely available on some older Linux distributions and embedded systems yet.
This is to be phased out ~2025 (maintenance overhead, missing features etc. in gcc-13)

suppress GCC -Wmissing-field-initializers warning and add gcc-13 (backward compatibility)

---

blocks/basic/include/gnuradio-4.0/basic/DataSink.hpp
core/benchmarks/bm-nosonar_node_api.cpp
core/benchmarks/bm_Buffer.cpp
core/benchmarks/bm_HistoryBuffer.cpp
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/Buffer.hpp
core/include/gnuradio-4.0/BufferSkeleton.hpp
core/include/gnuradio-4.0/CircularBuffer.hpp
core/include/gnuradio-4.0/ClaimStrategy.hpp
core/include/gnuradio-4.0/Message.hpp
core/include/gnuradio-4.0/Port.hpp
core/include/gnuradio-4.0/Scheduler.hpp
core/include/gnuradio-4.0/WaitStrategy.hpp
core/test/qa_Block.cpp
core/test/qa_DynamicPort.cpp
core/test/qa_Port.cpp
core/test/qa_buffer.cpp

The bm_Buffer benchmark test indicated significant performance degradation for the multi-producer case following this commit: https://github.com/fair-acc/gnuradio4/commit/5bd3eed14076427b1d50997ae6c2a77863876121.
The `CircularBuffer` was significantly updated, it uses newly developed `AtomicBitset` to check for available slots.
Other changes:
* Remove CircularBuffer::Writer::publish() and update unit tests accordingly.
* `reserve()` and `tryReserve()`. Some functions still use blocking `reserve()`.
* Fix the issue with the unintentionally disabled `HAS_POSIX_MAP_INTERFACE`.
* Updated `qa_buffer` to always test four variants: Multi-Posix, Multi-Portable, Single-Posix, Single-Portable.
Known issues:
* `warning: implicit conversion changes signedness: 'signed_index_type' (aka 'long') to …

Performance optimization for MultiThreadedStrategy

---

core/include/gnuradio-4.0/ClaimStrategy.hpp
core/include/gnuradio-4.0/Sequence.hpp

Currently, suppressing deprecation warnings for `std::atomic_load_explicit` and `std::atomic_compare_exchange_weak` methods. Note: While `std::atomic<std::shared_ptr<std::vector<std::shared_ptr<Sequence>>>>` is compatible with GCC, it is not yet supported by libc++.
This workaround is necessary to maintain compatibility and avoid deprecation warnings in GCC. For more details, see the following example implementation: https://godbolt.org/z/xxWbs659o
Revisit this code once libc++ adds support for `std::atomic<std::shared_ptr<std::vector<std::shared_ptr<Sequence>>>>`.

suppressing deprecation warnings for  atomic_load_explicit and atomic_compare_exchange_weak methods

---

blocks/basic/include/gnuradio-4.0/basic/DataSink.hpp
core/include/gnuradio-4.0/AtomicBitset.hpp
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/CircularBuffer.hpp
core/include/gnuradio-4.0/ClaimStrategy.hpp
core/include/gnuradio-4.0/Port.hpp
core/test/CMakeLists.txt
core/test/qa_AtomicBitset.cpp
core/test/qa_buffer.cpp

Performance optimization for MultiProducerStrategy
* AtomicBitset bulk set/reset
* Rename to Single(Multi)ProducerStrategy
* Eliminate usage of reserve(), use tryReserve() instead
* Remove warnings
```text
┌──────────────────benchmark:──────────────────┬──────┬──CPU branch misses───┬─ops/s─┬──mean──┬─<CPU-I>─┬───CPU cache misses────┬─stddev─┬─#N─┬─CTX-SW─┬─total time─┬──min───┬─median─┬──max───┐
│                                              │ SKIP │                      │       │        │         │                       │        │    │        │            │        │        │        │
│    POSIX: 1 producers -< 1  >-> 1 consumers  │ PASS │ 63.3k / 546k = 11.6% │ 25.8M │  39 ms │    317m │  13.3k / 100k = 13.2% │   8 ms │ 8  │   105  │     310 ms │  31 ms │  36 ms │  58 ms │
│    POSIX: 1 …
```

Performance optimization for MultiProducerStrategy

---

core/include/gnuradio-4.0/ClaimStrategy.hpp
core/test/qa_buffer.cpp

This fixes the case where setSlotStates is called with (n, n + size). Before that would lead to no Slots being published, now it should correctly update the buffer.
This bug can only be reproduced on low-core machines ore by increasing the number of writers in qa_buffer MultiProducerStdMapMultipleWriters.
fixes #380
Since I wasn't that deep into the code over there, I mainly concentrated on the diff of the commit introducing the failures. I could trace the problem to `ClaimStategy::setSlotsStates(...)` where uncommenting the non-bulk update of the AtomicBitset solved the issue. Invoking the non-bulk API one level deeper still caused the problem, so the problem had to be in that function itself.
The change now should make the bulk API behave the same way as the non-bulk one. Since this is …

ClaimStrategy: fix bulk update of AtomicBitset

---

blocks/basic/test/qa_PythonBlock.cpp

All tests for `qa_PythonBlock` are now passing again.
The behavior of `Settings` changed after the introduction of `CtxSettings`. Unlike before, `CtxSettings` are not initialized in the `Block` constructor. Instead, a separate `Block::init(...)` function must be called. 
This change was necessary we need to determine which parameters are provided by the user and which should be set to default values, which is not possible in the Block constructor.
The `Block::init()` function internally calls `CtxSettings::init()` and `CtxSettings::applyStagedParameters()` to handle this initialization process.

Fix qa_PythonBlock failed tests.

---

core/include/gnuradio-4.0/Settings.hpp
core/include/gnuradio-4.0/Tag.hpp
meta/include/gnuradio-4.0/meta/formatter.hpp
meta/test/qa_formatter.cpp

* code and templating structure (via and in response to -ftime-trace analysis)
* replaced std::ranges::find(..) by more compile-time friendly version
* replaced std::sort by binary-search+merge-sort
* added non-inline to methods to avoid unnecessary compile-time optimisations
* optimised custom pmtv formatted by reducing the `std::visit(...)` pattern (not yet fully eliminated.
Compile-time differences (~4% ... hoped to be more, but it's a start).
**before:**
```text
real    20m21.229s
user    89m12.953s
sys     3m8.205s
```
**this PR:**
```text
real    19m33.855s
user    85m44.586s
sys     3m35.693s
```
ClangAnalyser profile with this PR (based on Clang's `-ftime-trace` feature) in the `./build` directory:
```bash
ClangBuildAnalyzer --all . gr4_all_before.bin; ClangBuildAnalyzer --analyze …
```

refactored & simplified Settings.hpp and pmtv format

---

CMakeLists.txt
bench/benchmark.hpp
blocks/http/test/CMakeLists.txt
core/benchmarks/bm_Buffer.cpp
core/include/gnuradio-4.0/WaitStrategy.hpp
core/include/gnuradio-4.0/thread/thread_affinity.hpp
core/test/qa_buffer.cpp
core/test/qa_grc.cpp
core/test/qa_thread_affinity.cpp
core/test/qa_thread_pool.cpp

This PR focuses on compiling and running GNU Radio 4 on macOS.
- Several adjustments were made to ensure compatibility and successful execution on macOS.
- Tested on macOS 14.6.1 with both `gcc-13` and `gcc-14` installed via Homebrew.
- Encountered issues with the `libc++` library when using `clang-18`; the default Apple compiler is `clang-15`.
- **HttpBlock**: Disabled due to compatibility issues with MacOsSDK. Further investigation is needed if support is required.
- **Thread Affinity**: Currently not supported. Further investigation may be required if needed.

Partial support of MacOs

---

core/benchmarks/bm_HistoryBuffer.cpp

This benchmark was missed in the update in 3521e96fdb138cce075c6385a201e88eaa63e95b.
Co-authored-by: @drslebedev

Fix reading published sample

---

LICENSE
README.md

This commit adds the LGPLv3 linking exception to handle GR4 as a header-only library. The exception allows proprietary applications to link and use GR4 without disclosing their source code, addressing legal and operational constraints (e.g., in government or security-sensitive applications).
This is particularly important since traditional dynamic or static linking isn't applicable in header-only libraries. Modifications to GR4 itself remain LGPL-compliant, ensuring continued adherence to copyleft and FLOSS principles while enabling wider adoption.
By including this exception, we aim to increase the flexibility for adoption by public organisations, critical infrastructure, and industry partners, while maintaining the core FLOSS principles.

add LGPLv3 linking exception for header-only GR4

---

blocks/basic/include/gnuradio-4.0/basic/StreamToDataSet.hpp
blocks/basic/test/qa_StreamToDataSet.cpp

* Support several parallel DataSet accumulation
* Support sample accumulation between work() iterations
* Update unit tests
Notes:
- `n_pre` must be less than the size of the output port's `CircularBuffer`. The blok waits until all `n_pre` samples can be written to the output in a single iteration.
- In stream-to-stream mode, the "stop" Tag is not included in the output.
- Stream-to-stream mode has limited support for overlapping triggers. Configurations such as Start-Stop-Start-Stop work as expected, but configurations like Start-Start-Stop-Stop result in undefined behavior. If data accumulation is active, the second "start" is ignored, and the output may vary depending on subsequent tags.
- In stream-to-dataset modes, the "stop" Tag is included in the DataSet output.
- Tags for …

Update of StreamToDataSet block

---

core/include/gnuradio-4.0/Settings.hpp

Make this function inline to allow code including Settings.hpp to be split over several compilation units.

settings: make comparePmt() inline

---

core/include/gnuradio-4.0/WaitStrategy.hpp

This fixes and error when cross-compiling for ARM processors.  The ARM asm equivalent to rep/nnop is yield.

Adding the assembly yeild command to support noop for ARM

---

.github/workflows/ci.yml
CMakeLists.txt

Reading diagnostics with ANSI color codes in between is unnecessarily hard. We now make use of the cmake documented switch to control color output. And we only force color on if the tooling suggest it might be necessary.

CMake: Default color diagnostics to force-on with ccache/ninja

---

core/include/gnuradio-4.0/Block.hpp
core/test/qa_Block.cpp

This makes `reflFirstTypeName<std::complex<float>>()` return `"std::complex<float>"s` instead of `"std::complex<T>"s`, and likewise for `std::complex<double>`.

Block: add std::complex as a special case in reflFirstTypeName

---

blocks/soapy/include/gnuradio-4.0/soapy/Soapy.hpp
blocks/soapy/include/gnuradio-4.0/soapy/SoapyRaiiWrapper.hpp

Avoid reference to stdlib function which is unspecified (possibly ill-formed):
https://eel.is/c++draft/library#namespace.std-6
Use std::tie instead of std::forward_as_tuple.
The former creates a tuple of lvalue references, the latter can additionally hold rvalue references, which is not the intent here.

Minor soapy cleanups

---

core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/BlockTraits.hpp
core/include/gnuradio-4.0/Port.hpp
core/test/qa_Block.cpp
core/test/qa_Port.cpp
core/test/qa_Tags.cpp

As outlined in #407 I.) this PR introduces a way to directly access and consume tags on the current ConsumableSpan by introducing a `tags()` function which will return a view of all tags with the indices shifted to correspond to the local span indices and a `consumeTags(untilLocalIndex = 1)` which will consume all tags up to the local sample index in the span. The original Tags with the global index can still be accessed via the `rawTags` member.
This is mostly done, there is still a small issue with the concept for the `tags()` function, which is for now commented out and has to be either fixed or removed.

ConsumableInputPortRange Tag API

---

core/CMakeLists.txt
core/include/gnuradio-4.0/Graph_yaml_importer.hpp
core/include/gnuradio-4.0/Settings.hpp
core/include/gnuradio-4.0/YamlUtils.hpp
core/src/CMakeLists.txt
core/test/qa_HierBlock.cpp
core/test/qa_grc.cpp

This PR adds the capability to load and save context settings. This feature is particularly useful for blocks that maintain multiple parameter sets for different contexts, such as the `FunctionGenerator` block. With these changes, the `FunctionGenerator` can now be properly saved to and loaded from a YAML file.
```cpp
auto&      block = graph1.emplaceBlock<ArraySink<double>>({{"name", "ArraySink0"}});
const auto now   = settings::convertTimePointToUint64Ns(std::chrono::system_clock::now());
expect(block.settings().set({{"name", "ArraySink1"}}, SettingsCtx{now, "1"}).empty());
expect(block.settings().set({{"name", "ArraySink1+10"}}, SettingsCtx{now + 10'000'000'000ULL, "1"}).empty());
expect(block.settings().set({{"name", "ArraySink1+20"}}, SettingsCtx{now + 20'000'000'000ULL, …
```

YAML support for context settings

---

blocks/basic/include/gnuradio-4.0/basic/DataSink.hpp
blocks/basic/test/qa_DataSink.cpp

Add sink to export DataSet<T> streams. This block is a simpler DataSink
(which operates of non-DataSet streams), basically handing out the
incoming data sets as is, allowing basic filtering.

Add DataSetSink block

---

core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/BlockTraits.hpp
core/include/gnuradio-4.0/Port.hpp
core/test/qa_HierBlock.cpp

Currently, our implementation does not check whether a port is connected or if it is synchronous or asynchronous. We calculate the minimum number of processed samples across input and output ports, and only if both processedIn > 0 and processedOut > 0 do we forward tags.
This PR introduces a check to determine if a port is connected, which partially addresses the issue.
This PR helps to fix tag forwarding prolem for `Picoscope` block.
See https://github.com/fair-acc/gnuradio4/issues/444 for more explanations.

Check if a port is connected or not

---

core/test/qa_Block.cpp
core/test/qa_Messages.cpp

After making changes to ClockSource and fixing a bug where it wasn't functioning properly (see https://github.com/fair-acc/gnuradio4/pull/449), I noticed that the `qa_Message` test named "Settings handling via scheduler" started failing.
Previously, the test used ClockSource, which essentially produced no samples due to the bug. After my fix, the test began to fail because `ClockSource` started producing samples as expected.
Upon further investigation, I found that the issue isn't with the message handling but rather with BlockingIO—since `ClockSource` has the `BlockingIO` attribute. I created a small unit test that reproduces the error reliably.
The core problem is that` ClockSource` continues running in a separate thread for some time, and the detection mechanism to determine whether it …

Fix qa_Message

---

blocks/math/include/gnuradio-4.0/math/Math.hpp
blocks/math/test/qa_Math.cpp

To learn how to implement blocks in gr4 I want to implement and contribute a simple math block as part of the Block Tutorial at [European GNU Radio Days 2024](https://events.gnuradio.org/event/23). This PR is a work-in-progress state of my efforts.
- Add
- Divide
- Multiply
- Subtract
**Usage example:**
```cpp
gr::Graph graph{};
// source_1 counting 1,2,3,4,...,10
auto& source_1 = graph.emplaceBlock<gr::testing::CountingSource<float>>({{"n_samples_max", 10U}});
// source_2 counting 6,7,8,9,...,15
auto& source_2 = graph.emplaceBlock<gr::testing::CountingSource<float>>({{"n_samples_max", 10U}});
source_2.default_value = 5.0f;
// Add block with two inputs
auto& adder = graph.emplaceBlock<gr::math::Add<float>>({{"n_inputs", 2U}});
// Null sink
auto& sink = …
```

Add blocks: Multiply, Divide, Add, Subtract

---

core/include/gnuradio-4.0/BlockModel.hpp
core/test/qa_HierBlock.cpp

needed to pass some optional non-global UI constraints to the specific block e.g. in case the same block is redrawn in two different UI views.

extended BlockModel::draw(const property_map&) API

---

algorithm/include/gnuradio-4.0/algorithm/dataset/DataSetUtils.hpp
blocks/basic/include/gnuradio-4.0/basic/DataSink.hpp
blocks/basic/include/gnuradio-4.0/basic/StreamToDataSet.hpp
blocks/basic/include/gnuradio-4.0/basic/clock_source.hpp
blocks/basic/test/qa_DataSink.cpp
blocks/basic/test/qa_StreamToDataSet.cpp
blocks/fileio/include/gnuradio-4.0/fileio/BasicFileIo.hpp
blocks/testing/include/gnuradio-4.0/testing/ImChartMonitor.hpp
blocks/testing/include/gnuradio-4.0/testing/TagMonitors.hpp
blocks/testing/include/gnuradio-4.0/testing/bm_test_helper.hpp
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/BlockTraits.hpp
core/include/gnuradio-4.0/Buffer.hpp
core/include/gnuradio-4.0/BufferSkeleton.hpp
core/include/gnuradio-4.0/CircularBuffer.hpp
core/include/gnuradio-4.0/ClaimStrategy.hpp
core/include/gnuradio-4.0/DataSet.hpp
core/include/gnuradio-4.0/Port.hpp
core/include/gnuradio-4.0/Sequence.hpp
core/include/gnuradio-4.0/Tag.hpp
core/include/gnuradio-4.0/WaitStrategy.hpp
core/test/qa_PerformanceMonitor.cpp
core/test/qa_Port.cpp
core/test/qa_Scheduler.cpp
core/test/qa_Settings.cpp
core/test/qa_Tags.cpp
core/test/qa_buffer.cpp

This PR changes sequence and tag index types to unsigned (std::size_t).
There's three cases where we need relative tag indices though:
- Port::tags() provides the tags with indices relative to stream position. (these are of typestd::pair<index,map> anyway, so no extra type needed)
- DataSet::timing_events are relative to the first sample in the set, and can
be negative (e.g. for DataSink's snapshot acquisition mode, the trigger is
in the past.
- DataSink callback and pollers use tags relative to the current data chunk.
For the latter two, use RelativeIndexTag, which have a signed index type.
This doesn't actually handle overflow of the std::size_t, which I think would be an issue in the CircularBuffer impl (which relies on monotonously growing indices), so the question is if an overflow …

Switch Sequence and Tag indices to unsigned

---

blocks/basic/include/gnuradio-4.0/basic/Selector.hpp
blocks/basic/test/qa_Selector.cpp
blocks/testing/include/gnuradio-4.0/testing/TagMonitors.hpp
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/Port.hpp
core/include/gnuradio-4.0/Tag.hpp
core/include/gnuradio-4.0/annotated.hpp
core/test/qa_Block.cpp
core/test/qa_Tags.cpp

The changes include:
* Removed TagPropagationPolicy and introduced NoDefaultTagForwarding
* Resolved tag forwarding for scenarios where some output ports are `Async` and lack samples (Closes #444)
* Updated Selector block as a test case and example for manual tag forwarding (#452)
* Added `synch_combined_ports` parameter and possibility to have item-by-item interleaved output for multi mapped output ports
* Added tag propagation test to qa_Selector
* Added back pressure test to qa_Selector
* Added unit test in qa_Block to handle cases where input_chunk_size > 1 and input range has multiple tags
* Fix: Port::consumeTags to make untilLocalIndex exclusive
* Fix: Port::mergedTag to make untilLocalIndex exclusive
* Fix: TagMonitor to limit nSamples to the remaining samples for processing …

Manual Tag Forwarding with InputSpan and OutputSpan API

---

algorithm/include/gnuradio-4.0/algorithm/filter/FilterTool.hpp
blocks/CMakeLists.txt
blocks/electrical/CMakeLists.txt
blocks/electrical/include/gnuradio-4.0/electrical/PowerEstimators.hpp
blocks/electrical/test/CMakeLists.txt
blocks/electrical/test/qa_PowerEstimators.cpp
blocks/filter/include/gnuradio-4.0/filter/time_domain_filter.hpp
blocks/filter/test/qa_FrequencyEstimator.cpp
blocks/filter/test/qa_filter.cpp
meta/include/gnuradio-4.0/meta/UncertainValue.hpp
meta/test/qa_UncertainValue.cpp

This pull request introduces new blocks and features to enhance power system analysis capabilities, along with supporting uncertainty propagation through `UncertainValue<T>`. It also includes minor fixes and improvements across the codebase.
- **Functionality**: Computes per-phase:
- Active Power (P)
- Reactive Power (Q)
- Apparent Power (S)
- RMS Voltage (U_rms)
- RMS Current (I_rms)
- **Features**:
- Supports both single-phase and multi-phase electrical systems (`nPhases` as a non-type template parameter).
- Processes voltage and current inputs, applies low-pass filters to calculate average values.
- Outputs decimated results at a specified rate.
- **Functionality**: Calculates power factor and phase angle for each phase using active power (P) and apparent power (S) inputs.
- …

Implement PowerMetrics, PowerFactor, SystemUnbalance Blocks, and Configurable Filters with UncertainValue<T> Support

---

blocks/basic/include/gnuradio-4.0/basic/StreamToDataSet.hpp
blocks/basic/include/gnuradio-4.0/basic/SyncBlock.hpp
blocks/basic/test/CMakeLists.txt
blocks/basic/test/qa_SyncBlock.cpp
core/benchmarks/CMakeLists.txt
core/benchmarks/bm_sync.cpp
core/include/gnuradio-4.0/HistoryBuffer.hpp
core/include/gnuradio-4.0/Tag.hpp
core/test/qa_buffer.cpp

- This PR introduces a `SyncBlock` to synchronize data streams across multiple inputs that have the same sample rate. 
- It addresses key scenarios including initial time shifts, clock drift, and significant delays. 
- The `SyncBlock` synchronises input samples based on synchronization tags and publishes desynchronization tags with information about number of samples that were dropped.
- Add `bm_sync` for performance comparison
```
┌──────────────benchmark:───────────────┬──────┬──CPU branch misses───┬─ops/s─┬──mean──┬─<CPU-I>─┬───CPU cache misses───┬─stddev─┬─#N─┬─CTX-SW─┬─total time─┬─min─┬─median─┬─max─┐
│ src->gr::basic::SyncBlock<int>->sink  │ PASS │ 3.10M / 382M =  0.8% │  4.7G │ 843 ms │    930m │ 494M / 1.77G = 27.9% │        │    │     1  │     843 ms │     │        │     │
│ …
```

Implement SyncBlock

---

core/benchmarks/CMakeLists.txt
docker/Dockerfile

The Emscripten issue, likely caused by resource exhaustion, was introduced in [PR #456](https://github.com/fair-acc/gnuradio4/pull/456). 
This PR fixes the problem by bumping to the new Emscripten version and removing benchmark tests from compilation.
The `qa_Message` test failed due to the new tests added in [PR #456](https://github.com/fair-acc/gnuradio4/pull/456). This issue went unnoticed because the same PR also introduced the Emscripten resource exhaustion problem.

Bump Emscripten version to 3.1.66

---

blocks/basic/test/qa_SyncBlock.cpp

This PR fixes qa_Sync test.
The problem was in incorrect data type for `N_DROPPED_SAMPLES` key when comparing received and expected tags.

Fix qa_Sync test

---

core/include/gnuradio-4.0/Block.hpp
core/test/qa_Messages.cpp

Issue here is that on WASM we have offsets added to our Context.time which then get's out of sync to what the client sent.

Fix qa_Messages on Emscripten build

---

CMakeLists.txt
core/include/gnuradio-4.0/YamlPmt.hpp
core/test/CMakeLists.txt
core/test/qa_YamlPmt.cpp

This implements serialization and deserialization of pmtv::map_t to a subset YAML 1.2.
It doesn't support the full YAML 1.2 standard, but rather focuses to serialize any possible pmtv::map_t value to valid YAML and back.

Implement YAML <-> pmtv::map_t generator and parser

---

core/include/gnuradio-4.0/Block.hpp
core/test/qa_Messages.cpp

Also always return current active context time when set/get

Return a message when a Settings Context is removed

---

algorithm/include/gnuradio-4.0/algorithm/SchmittTrigger.hpp
algorithm/test/CMakeLists.txt
algorithm/test/qa_SchmittTrigger.cpp
blocks/basic/include/gnuradio-4.0/basic/ConverterBlocks.hpp
blocks/basic/include/gnuradio-4.0/basic/Trigger.hpp
blocks/basic/test/CMakeLists.txt
blocks/basic/test/qa_TriggerBlocks.cpp
blocks/testing/include/gnuradio-4.0/testing/ImChartMonitor.hpp
meta/include/gnuradio-4.0/meta/UncertainValue.hpp
meta/include/gnuradio-4.0/meta/formatter.hpp
meta/test/qa_formatter.cpp

This PR introduces a new digitial `SchmittTrigger` block with configurable threshold and offset, as well as sub-sample edge timing interpolation options.
- **Edge Detection**: detects rising and falling edges based on user-defined `threshold` and `offset` values.
- **Uncertainty Support**: Propagates uncertainties and provides precise edge timing with associated errors.
- **Interpolation Methods**: Supports multiple methods for sub-sample precision:
- `NO_INTERPOLATION`: basic detection without interpolation.
- `BASIC_LINEAR_INTERPOLATION`: simple linear interpolation between adjacent samples.
- `LINEAR_INTERPOLATION`: linear regression over the samples within the threshold window.
- `POLYNOMIAL_INTERPOLATION`: (TODO) Placeholder for future implementation using Savitzky–Golay filters.
- …

Add Schmitt Trigger Block with Uncertainty Support and Optional Interpolation

---

core/include/gnuradio-4.0/YamlPmt.hpp
core/test/qa_YamlPmt.cpp

* Make sure block-style maps in block-style lists are parsed
correctly. This is needed to parse our existing GRC files.
```
- name: foo
id: bar
```
* Support unexpected whitespace/newlines between key and scalars
as well as flow-style maps/lists. E.g.
```
string:
"foo"
list:
[]
map: {
}
```

PmtYaml: Parser fixes

---

core/include/gnuradio-4.0/Block.hpp

Because the variadic template could also match for zero type parameters, this created an ambiguous template definition with the function above it.

Block: disambiguate registerBlock function

---

core/include/gnuradio-4.0/YamlPmt.hpp
core/test/qa_YamlPmt.cpp

Don't interpret ":" as key/value separator when followed by a non-whitespace character.

PmtYaml: Fix parsing of colons

---

CMakeLists.txt

* set relative path for exprtk
* set optimisation flags to max '-O2' to alleviate CI build times
* set absolute hash for pmt dependency
_N.B. performance difference between `-O2` vs. '-03' proved to be insignificant. ExprTk has about 30% ops/s compared to the natively executed function expression. See chart below for details:_

updated build system

---

blocks/basic/include/gnuradio-4.0/basic/FunctionGenerator.hpp
blocks/basic/include/gnuradio-4.0/basic/SignalGenerator.hpp
blocks/basic/include/gnuradio-4.0/basic/clock_source.hpp
blocks/basic/test/qa_StreamToDataSet.cpp
blocks/basic/test/qa_TriggerBlocks.cpp
blocks/basic/test/qa_sources.cpp
blocks/testing/test/qa_UI_Integration.cpp

as discussed: changed ClockSource output port to always return 'std::uint8_t' as default data type for timing-only, clock-type and other usages where the vertical signal value is only of secondary importance.

ClockSource T -> std::uint8_t fix

---

blocks/basic/include/gnuradio-4.0/basic/Selector.hpp

*A selector block with sign fixes galore — or at least three*
This PR primarily removes GCC/Clang sign-conversion warnings by explicitly casting from std::size_t to std::ptrdiff_t where needed. Otherwise, no major new features -- just a small patch compatible with the time after a *“Christmas induced food coma”* and to minimise compiler warnings ... 
*Did I mention that I love unit tests? Thanks to @drslebedev!*

XMas-Day-2: Selector block: fix sign-conversion warnings & minor cleanup

---

blocks/math/include/gnuradio-4.0/math/Rotator.hpp
blocks/math/test/CMakeLists.txt
blocks/math/test/qa_Rotator.cpp

*A Rotator block i.e fixed frequency shifter*
- Introduce Rotator block that increments the phase before rotating each sample.
- handles angle wrapping to keep accumulated_phase in [0, 2π).
for more info see [here](https://wiki.gnuradio.org/index.php?title=Rotator).
Some visual unit-test examples:

XMas-Day-3: added Rotator block fixed frequency shifter

---

core/include/gnuradio-4.0/HistoryBuffer.hpp
core/test/qa_buffer.cpp

*A ring buffer with push_front and pop—how jolly can that be?*
This PR **refines** the `HistoryBuffer` by introducing or improving:
1. **\`push_front(...)\`**: Lets you store elements so the *oldest* ends up at index \[0\].  
2. **\`pop_front()\` & \`pop_back()\`**: Remove elements from the logical front/back of the ring.  
3. **\`front()\` & \`back()\`**: Simple, direct access to the first/last elements in logical order.  
4. **\`resize(size_t)\`** (for dynamic-extent): Resize capacity while retaining existing items.  
5. **Documentation**: We’ve updated our doxygen comments to show how these new methods work, plus concise code examples illustrating “newest-at-\[0\]” vs. “oldest-at-\[0\].”
Along the way, we trimmed some unneeded modulo operations for single-step increments, simplified …

XMas-Day-1: HistoryBuffer: added push_front method, iterator constraints, and resize

---

blocks/basic/include/gnuradio-4.0/basic/FunctionGenerator.hpp

Small fix of the `FunctionGenerator`: reset current time only if signal type was changed.

Fix FunctionGenerator

---

algorithm/include/gnuradio-4.0/algorithm/SchmittTrigger.hpp
algorithm/include/gnuradio-4.0/algorithm/filter/FilterTool.hpp
algorithm/test/qa_FilterTool.cpp
blocks/basic/include/gnuradio-4.0/basic/DataSink.hpp
blocks/basic/include/gnuradio-4.0/basic/StreamToDataSet.hpp
blocks/basic/include/gnuradio-4.0/basic/SyncBlock.hpp
blocks/electrical/include/gnuradio-4.0/electrical/PowerEstimators.hpp
blocks/filter/include/gnuradio-4.0/filter/FrequencyEstimator.hpp
blocks/filter/include/gnuradio-4.0/filter/time_domain_filter.hpp
blocks/testing/include/gnuradio-4.0/testing/ImChartMonitor.hpp
core/benchmarks/bm_HistoryBuffer.cpp
core/include/gnuradio-4.0/HistoryBuffer.hpp
core/include/gnuradio-4.0/Scheduler.hpp
core/test/qa_buffer.cpp

should (hopefully) simplify and provide a more intuitive the naming.
- Dynamic (`N == std::dynamic_extent`): uses `std::vector<T>` (size = 2 * capacity).
- Fixed (`N != std::dynamic_extent`): uses `std::array<T, N * 2>`.
- `push_front(const T&)`: Add new item, drop oldest if full, index `[0]` is newest.
- `push_back(const T&)`: Add new item, drop oldest if full, index `[0]` is oldest.
- `pop_front()`, `pop_back()`: Remove from logical front/back of the ring.
- `front()`, `back()`: Returns the first/last item in logical order.
- `operator[](i)`, `at(i)`: Unchecked/checked access.
- `resize(...)` (dynamic-only): Adjust capacity, preserving existing data.
- `get_span(...)`: Obtain a contiguous view across wrap boundaries.
```cpp
gr::history_buffer<int, 5> hb_newest;   // use push_front -> …
```

HistoryBuffer<T> flipped push_back<->push_front naming

---

core/include/gnuradio-4.0/PmtTypeHelpers.hpp
core/include/gnuradio-4.0/Settings.hpp
core/include/gnuradio-4.0/YamlPmt.hpp
core/test/CMakeLists.txt
core/test/qa_PmtTypeHelpers.cpp
core/test/qa_YamlPmt.cpp
core/test/qa_grc.cpp

**Summary of Changes:**
1. **YamlPmt improvements (first commit)**  
- Replaced overly broad use of `auto` with explicit types for clarity and safer conversions.  
- Fixed lifetime issues with `string_view::data()` by constructing proper `std::string` copies where needed.  
- Ensured correct usage of `std::iscntrl`, `std::isspace`, etc. by casting to `unsigned char`, as required by the C++ standard to avoid undefined behaviour.  
- Added a new helper function `formatAsLines(...)` to annotate lines and columns for YAML syntax errors, simplifying debugging.
```cpp
// example snippet showing the new usage of formatAsLines:
auto errorMsg = pmtv::yaml::formatAsLines(yamlInput, parseError);
std::cerr << "Parse error:\n" << errorMsg << std::endl;
```
**Example output:**
```text
Unexpected …
```

YamlPmt improvements, safe type conversions, and lenient numeric parser

---

core/CMakeLists.txt
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/BlockModel.hpp
core/include/gnuradio-4.0/Graph.hpp
core/include/gnuradio-4.0/PmtTypeHelpers.hpp
core/include/gnuradio-4.0/Settings.hpp
core/src/PmtTypeHelpers.cpp
core/src/Settings.cpp
core/test/CMakeLists.txt

* pre-instantiate settings `convert_safely<..>` handler for common types and push implementation into static lib
* replaced `std::function<(lambda ...>>` in 'BlockModel' with more basic member function pointers.
... should help improve the overall and per-unit compilation time
```markdown
| Configuration       |   Parsing (frontend) [s] |   Codegen & opts (backend) [s] 
|:--------------------|-------------------------:|-------------------------------:|
| before: w/o plugins |                     69.4 |                          135.2 |
| before: w/ plugins  |                    540.8 |                          813.9 |
| after: w/o plugins  |                     54.5 |                          130.8 |
| after: w/ plugins   |                    388.5 |                          715.1 |
``` …

refactored sub-components to be statically compiled & linked

---

blocks/basic/include/gnuradio-4.0/basic/DataSink.hpp
blocks/basic/include/gnuradio-4.0/basic/StreamToDataSet.hpp

This PR includes the following changes:
- Sets `DataSet` output as the default for the `StreamToDataSet` block.
- Updates `DataSetSink` to process the entire `DataSet` based on `signal_name`.

Updates in DataSetSink

---

blocks/basic/include/gnuradio-4.0/basic/DataSink.hpp
blocks/basic/test/qa_DataSink.cpp

The PR includes the following changes:
- DataSink cannot be registered with an empty string; it must be set either by the user or via a tag.
- The registration with the same signal name is not allowed.
- Fix qa_DataSink

Fix DataSinkRegistry

---

core/test/qa_Graph.cpp

When a block has multiple synchronous output ports, any unconnected port defaults to a buffer size of 4096. 
This default value can unintentionally limit all ports’ buffer sizes within `workInternal()` , resulting in chunk sizes constrained to 4096, even if larger buffers were explicitly configured for other ports. The issue is that the user may not notice it since no errors are printed.
A test has been included to replicate this behavior, similar to the Picoscope block, where one unconnected output port causes all output to be reduced to chunks of size 4096.
Current workaround is to connect unused ports to `NullSink`.

Add multi output ports test.

---

blocks/basic/include/gnuradio-4.0/basic/FunctionGenerator.hpp
blocks/basic/include/gnuradio-4.0/basic/clock_source.hpp
blocks/basic/test/qa_DataSink.cpp
blocks/basic/test/qa_StreamToDataSet.cpp
blocks/basic/test/qa_TriggerBlocks.cpp
blocks/basic/test/qa_sources.cpp
blocks/soapy/test/qa_Soapy.cpp
blocks/testing/test/qa_UI_Integration.cpp
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/DataSet.hpp
core/include/gnuradio-4.0/Graph_yaml_importer.hpp
core/include/gnuradio-4.0/Port.hpp
core/include/gnuradio-4.0/Settings.hpp
core/include/gnuradio-4.0/Tag.hpp
core/include/gnuradio-4.0/TriggerMatcher.hpp
core/test/qa_Block.cpp
core/test/qa_Messages.cpp
core/test/qa_PerformanceMonitor.cpp
core/test/qa_Settings.cpp
core/test/qa_Tags.cpp
core/test/qa_TriggerMatcher.cpp

* CONTEXT needs to be always in the property-root, since this is also used outside the trigger logic. `TRIGGER_META_INFO` sub-property-map is kept (default: {}) for user-defined/hw-specific info.
* replaced `"context"` and `"sample_rate"` with `CONTEXT` and `SAMPLE_RATE` definition -> should simplify later refactoring
* FunctionGenerator block changes:
* added additional `trigger_...`diagnostics property fields
* added 'signal_trigger' parameter matcher/criteria
* `Packet<T>`, `Tensor<T>`, `DataSet<T>` changes:
*  changed to using straight `pmtv::map_t` type (easier move/copy operation)
* added `default_value` field for ZOH, range padding, interpolation purposes etc.

fix/standardised CONTEXT position in tag property_map

---

core/include/gnuradio-4.0/Block.hpp

Remove the `publishEoS` call for `BlockingIO<false>` because it introduces multi-threading issues.
- The `publishEoS` call was originally added as a safeguard to ensure the EOS tag is always published if someone implements their own `work()` method and forgets to publish `EoS` tag.
- However, this call is not thread-safe. Specifically, `publishEoS` does not publish immediately; it stores pending tags, and actual publishing happens later in the destructor when `workInternal()` finishes. This deferred mechanism can lead to race conditions in multi-threaded environments.
- If the user relies on the provided `invokeWork()` method rather than a custom `work() `method, EoS tag publication is already guaranteed. 
- Users implementing custom `work()` methods must ensure they handle EoS …

Remove the publishEoS call for BlockingIO<false>

---

core/src/utils.cpp
core/test/qa_PortableTypeName.cpp

Remove namespaces from the portable type name that start with a double underscore or with an underscore and a capital letter as these mark interal implemntation which is not portable. (which are reserved by std)

Remove private namespaces from the portable type name

---

blocks/basic/include/gnuradio-4.0/basic/FunctionGenerator.hpp
blocks/basic/test/qa_StreamToDataSet.cpp
core/include/gnuradio-4.0/Settings.hpp

-- non matching trigger should not trigger a function parameter change.
This is a workaround. We may need to look into a user-definable settings pre-condition check that are used to reject settings changes based on -- for example -- required trigger, internal block state, ctx etc.

fixed FunctionGenerator

---

algorithm/include/gnuradio-4.0/algorithm/ImChart.hpp
algorithm/include/gnuradio-4.0/algorithm/dataset/DataSetHelper.hpp
algorithm/include/gnuradio-4.0/algorithm/dataset/DataSetMath.hpp
algorithm/include/gnuradio-4.0/algorithm/dataset/DataSetTestFunctions.hpp
algorithm/include/gnuradio-4.0/algorithm/dataset/DataSetUtils.hpp
algorithm/include/gnuradio-4.0/algorithm/fourier/fft_common.hpp
blocks/basic/include/gnuradio-4.0/basic/StreamToDataSet.hpp
blocks/basic/test/qa_StreamToDataSet.cpp
blocks/fourier/include/gnuradio-4.0/fourier/fft.hpp
blocks/fourier/test/qa_fourier.cpp
blocks/testing/include/gnuradio-4.0/testing/ImChartMonitor.hpp
core/include/gnuradio-4.0/DataSet.hpp
meta/include/gnuradio-4.0/meta/UnitTestHelper.hpp

* added missing fields/init/defs for axis, meta-information, timing-events
* added 'checkDataSetConsistency(..)' helper functions
* added unit-test helper `[eq, approx]_collections` compatible with UT framework
* cleaned-up/simplified unit-test
* added visual representation
* renamed DataSet parameter idx names (should make the semantic more 'nomen-est-omen' for users of that API)
* changed from ramp to sine test-signal to better identify frequency mapping
* fixed complex-value FFT ordering (shift was missing)
- related: added optional boolean `shiftSpectrum` parameter to `compute[Magnitude, Phase]Spectrum(..)`
Additional minor fixes:
* ImChart: clamp DataSet signal names to chart width
* ImChart: add additional selected signal parameter (default: draw all)
* DataSetMath: added missing …

fixed FFT<T> block DataSet<T> output

---

blocks/soapy/test/qa_Soapy.cpp
meta/include/gnuradio-4.0/meta/formatter.hpp
meta/test/qa_formatter.cpp

- **soapy QA: make Range unambiguous**
- **formatters: Range format() should be const**
- **formatters: only implement std::expected formatter if fmt < 11.0.0**
The build of qa_formatters failed for reasons of lacking constness; so fixed that.
While I was at it, fixed related alias resolution ambiguity making soapy stuff ftb.
And since at that point it was worth trying: with this changeset, GR4 also builds with fmt 11, not only 10.

Fix formatters build on F41, make fmt11-proof

---

core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/Port.hpp
core/include/gnuradio-4.0/Settings.hpp
core/include/gnuradio-4.0/annotated.hpp
core/test/CMakeLists.txt
core/test/qa_Port.cpp
core/test/qa_Settings.cpp
core/test/qa_Tags.cpp

This PR  addresses the issue with tag propagation when decimation is used, it includes the following changes: 
* Initialise `autoForwardParameters` with `kDefaultTags`.
* Correctly forward tags when decimation is on:
* Introduce `BackwardTagForwarding` attribute
* Forward and backward tag propagation is supported
* Update `sample_rate` if the block performs decimation or interpolation

Tags forwarding

---

CMakeLists.txt
docker/Dockerfile

This PR includes the following:
- Resolves build failure when `clang-scan-deps` is missing.
- Enhances CMake logic to automatically locate the `clang-scan-deps` executable matching the Clang compiler version and sets `CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS`.
- Adds the `clang-tools` package to Docker to ensure the availability of `clang-scan-deps`.

Fix build failure if `clang-scan-deps` is not found. 

---

blocklib_generator/tools/parse_registrations.cpp
blocks/basic/test/qa_BasicKnownBlocks.cpp
blocks/libs/test/qa_KnownSharedLibBlocks.cpp
blocks/libs/test/qa_apptest_KnownStaticLibBlocks.cpp
core/test/qa_GraphMessages.cpp
core/test/qa_grc.cpp
core/test/qa_plugins_test.cpp

The header files were previously generated without the `.hpp` extension, causing naming conflicts: for example, the `qa_grc` test executable was incorrectly identified as a header file.
This PR resolves the issue by adding the `.hpp` extension to the blocklib headers, preventing these naming conflicts.
This minimal change directly addresses the immediate issue. However, future naming conflicts could still occur. Potential further enhancements include:
- Adding a `_blocklib` suffix to clearly indicate that the headers originate from the block library.
- Generating a structured directory layout such as `gr4/<libname>/<header_name>.hpp`, enabling users to explicitly reference headers even when name overlaps exist.

Add .hpp extension to the blocklib header to avoid name conflicts.

---

blocks/basic/test/qa_DataSink.cpp
blocks/testing/include/gnuradio-4.0/testing/TagMonitors.hpp
core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/Tag.hpp
core/test/qa_Settings.cpp
core/test/qa_Tags.cpp

This PR includes the following updates:
- Restrict auto-forwarding to only the tags defined in `Settings::autoForwardParameters`.
- Update existing tests accordingly.
- Add custom auto-forward tags in specific tests, for example in `qa_DataSink`:
```cpp
std::vector<std::string> customAutoForwardKeys = {"DAY", "MONTH", "YEAR"};
delay.settings().autoForwardParameters().insert(customAutoForwardKeys.begin(), customAutoForwardKeys.end());
```
- Change `gr::tag::N_DROPPED_SAMPLES` type to `gr::Size_t`
- Update `map_diff_report` to check also for missing keys from the second map.

Automatically forward tags only from Settings::autoForwardParameters

---

.github/workflows/ci.yml
CMakeLists.txt
algorithm/CMakeLists.txt
blocklib_generator/tools/parse_registrations.cpp
blocks/basic/src/CMakeLists.txt
blocks/soapy/CMakeLists.txt
docker/Dockerfile

* `MinSizeRel` default to `EMBEDDED` and performs stronger size optimisations and 'strip'-ing
* if enabled, debugging uses compressed debugging information `-gz` to reduce the build size
* added 'mold' and 'lld' as optional faster linker fallbacks to 'ld'.
* needed to update `exprtk` integration due to stricter `mold` linker and `-fLTO` requirements
* added cmake config, compiler, and link flag option debug output
* added `ENABLE_EXAMPLES` guards for examples in `../src` directories
* eliminated dead example code (function generator example)
* disabling LTO for exprtk for GCC13 due to known IPA/modref crash issues.
* added header include guards for generated block code
Signed-off-by: Ralph J. Steinhagen <r.steinhagen@gsi.de>
Example cmake-output (gcc13-Release + ASAN):
```cmake
-- …
```

made build type optimisation flags explicit

---

.github/workflows/ci.yml
CMakeLists.txt
blocks/basic/include/gnuradio-4.0/basic/StreamToDataSet.hpp
blocks/basic/test/qa_DataSink.cpp

This PR includes 3 commits:
1) Make unit tests running again.
Fix ‑ move `enable_testing()` and include(CTest) before any directory that adds tests, right after the option(ENABLE_TESTING …) block and before the first add_subdirectory().
2) Fix qa_DataSink test, add additinal checks.
Fix in StreamToDataSet: add timing_events only after pre samples are added.
3) Fix gcc-14 Coverage: workaround GCC #68080 by adding --gcov-ignore-parse-errors=negative_hits.warn_once_per_file to gcovr args

Make unit tests running again.

---

CMakeLists.txt

Executables linked with `libc++` where being linked against `gnuradio-blocklib-core.so` which pulled in libstdc++
Something I stumbled on while debugging an unrelated linker error.
I'm surprised tests are not crashing more often

Don't mix libc++ with libstdc++ in the same executable

---

blocks/basic/include/gnuradio-4.0/basic/DataSink.hpp
blocks/basic/test/qa_DataSink.cpp
blocks/basic/test/qa_PythonBlock.cpp
meta/include/gnuradio-4.0/meta/formatter.hpp

Each `.so` that included `DataSink.hpp` created its own `DataSinkRegistry`
instance (one per translation unit), so the executable and its plug‑ins
worked with different instances of `DataSinkRegistry`.
Make the singleton symbol visible process-wide using `__attribute__((visibility("default")))` :
```cpp
__attribute__((visibility("default")))
inline DataSinkRegistry& globalDataSinkRegistry() {
static DataSinkRegistry instance;
return instance;
}
```
exports the singleton with default visibility, giving the whole process a single, shared `DataSinkRegistry`.
Move the definition out of the header and into a single .cpp compiled into a common library, then drop both inline and the visibility attribute:

Fix problem with DataSinkRegistry singleton instances

---

blocks/basic/include/gnuradio-4.0/basic/CommonBlocks.hpp
blocks/math/CMakeLists.txt
blocks/math/include/gnuradio-4.0/math/ExpressionBlocks.hpp
blocks/math/include/gnuradio-4.0/math/Math.hpp
blocks/math/include/gnuradio-4.0/math/Rotator.hpp
core/test/qa_DynamicBlock.cpp

Math library was missing but it is needed for some flowgraph in `opendigitizer`.
Add math block library to generated plugins
* Remove obsolet `MultiAdder` block -> use `gr::blocks::math::Add` instead
* Some fixes in math block registration

Add math block library to generated plugins

---

meta/include/gnuradio-4.0/meta/formatter.hpp

... by adding pre-processor macro guards that can be re-used in other similar project or specifically suppress the GR4-based definitions.

qfix std::formatter ODR violations

---

blocks/basic/include/gnuradio-4.0/basic/StreamToDataSet.hpp

This fix is required for OD. Including the StreamToDataset.hpp header causes a compilation error due to a missing dependency.

Add missing BlockRegistry.hpp header to StreamToDataSet

---

blocks/testing/include/gnuradio-4.0/testing/NullSources.hpp

This is needed to connect picoscope block (in RapidBlock mode) digital output port if it is not used.

Support gr::DataSet<uint16_t> for NullSink block

---

core/include/gnuradio-4.0/YamlPmt.hpp
core/test/qa_YamlPmt.cpp

This PR addresses a problem where flow-style string sequences in YAML were not parsed correctly if there are no explicit quotes.
For example, in [A, B, C , D ], the resulting vector was ["A", "B", "C ", "D "], where some entries unintentionally included trailing spaces.
While scalar strings and maps were handled correctly, vector of strings in flow style were incorrectly parsed.
This fix ensures proper handling of such vectors.
Additionally, during serialization, strings that contain leading or trailing spaces are now always enclosed in quotes to preserve their content accurately.

YamlPmt: fix flow of strings issue with trailing spaces

---

core/include/gnuradio-4.0/AtomicBitset.hpp
core/test/qa_AtomicBitset.cpp

- exclude attempts to use boost::ut's aborts call in qa_AtomicBitset.cpp on win32.
- fixed AtomicBitset.hpp to use ULL instead of UL on win32 as std::size_t is unsigned long long on win32.

win32: fix for qa_AtomicBitset issue #585

---

blocks/basic/test/qa_PythonBlock.cpp

- removed argument myBlock.ioThreadPool in init call to myBlock.init
- I believe this was missed with the update to the thread Manager class. Without the changes, I can't get qa_PythonBlock.cpp to build.

Remove reference to PythonBlock's ioThreadPool member

---

algorithm/include/gnuradio-4.0/algorithm/ImChart.hpp
algorithm/test/example_ImChart.cpp
algorithm/test/qa_DataSetEstimators.cpp
algorithm/test/qa_FilterTool.cpp
algorithm/test/qa_ImChart.cpp
blocks/basic/test/qa_sources.cpp
blocks/math/test/qa_Rotator.cpp
blocks/testing/test/qa_UI_Integration.cpp
meta/include/gnuradio-4.0/meta/UnitTestHelper.hpp

- added windows.h include to ImChart.hpp
- added win32 call to SetConsoleOutputCP(UTF-8) to cpp programs built with ImChart.hpp
- added setlocale(C.UTF8) call to example_ImChart.cpp
- changed UL size specification to UZ, for std::min, std::max and std::clamp calls
- fixes https://github.com/fair-acc/gnuradio4/issues/584

Added support for ImChart.hpp in windows

---

bench/benchmark.hpp
blocks/basic/test/qa_TriggerBlocks.cpp
blocks/testing/include/gnuradio-4.0/testing/NullSources.hpp
blocks/testing/include/gnuradio-4.0/testing/TagMonitors.hpp
blocks/testing/test/CMakeLists.txt
blocks/testing/test/qa_NullSources.cpp
core/benchmarks/bm_Scheduler.cpp
core/include/gnuradio-4.0/Graph.hpp
core/include/gnuradio-4.0/Profiler.hpp
core/include/gnuradio-4.0/Scheduler.hpp
core/include/gnuradio-4.0/Tag.hpp
core/test/qa_HierBlock.cpp
core/test/qa_Scheduler.cpp
core/test/qa_SchedulerMessages.cpp

* added `SimCompute<T>` block to simulate compute delay and model latency effects for a given complexity order
* added unit-tests for Null[Source, Sink], Counting[Sink, Source], ...
* renamed _jobList to _executionOrder (better naming)
* corrected latency statistic print-out in benchmark.hpp
* added DFS scheduler, and added benchmark added cases
* A - linear graph
* B - forked graph
* C - split graph
* fixed bug by removing _blockList class member field in BFS and DFS scheduler (block list got duplicated on each init())
* added property_map constructor to SchedulerBase
Example output (N.B. 'first-out -> first-in' latency):

updated bm_Scheduler

---

meta/include/gnuradio-4.0/meta/formatter.hpp

- fix for https://github.com/fair-acc/gnuradio4/issues/586
- formatter.hpp uses colons in the representation of getIsoTime(), these colons are used in filenames in the BasicFileIo.hpp _actualFileName member varlable.  unfortunately the colons are not allowed in the filenames in windows as it is reserved for c:, etc.
- replaced the use of colons with underscores.
- FWIW, i tried using utf-8 characters instead of the colon and it broke the test, so I settled on underscores.

win32: fix for qa_FileIo.exe

---

blocks/libs/test/qa_KnownSharedLibBlocks.cpp

- in win32 std::size_t is unsigned long long and in linux it's unsigned long.  So the string retured by the registry under windows for gr::electrical::PowerMetrics is gr::electrical::PowerMetrics<float32, 3ull> rather than gr::electrical::PowerMetrics<float32, 3ul>. Used if-def macro to test the different expected string values.
- fixes issue https://github.com/fair-acc/gnuradio4/issues/587

win32: fix for qa_KnownSharedLibBlocks.exe

---

core/include/gnuradio-4.0/thread/thread_pool.hpp

Otherwise they cannot be initialized with custom implementations, because the default pools will be initialized with the first access to the manager.
On emscripten this resulted in requesting to many threads from the scheduler.

thread_pool::Manager: initialize default pools lazyly

---

core/include/gnuradio-4.0/thread/thread_pool.hpp

Since users of the thread pool manager can also access the default pools via their standard names using `Manager::get(string)` it was not ensured that the default pools were always available.

Revert "thread_pool::Manager: initialize default pools lazyly"

---

blocks/soapy/include/gnuradio-4.0/soapy/Soapy.hpp
core/benchmarks/bm_Buffer.cpp
core/include/gnuradio-4.0/HistoryBuffer.hpp
core/include/gnuradio-4.0/Scheduler.hpp
core/include/gnuradio-4.0/thread/MemoryMonitor.hpp
core/include/gnuradio-4.0/thread/thread_pool.hpp

- Soapy.hpp needs a static_cast<long int> to build.
- bm_Buffer.cpp needs to conditionally exclude _WIN32 for setCpuAffinity even though we have the required headers.  We also need a UL to UZ type change.
- HistoryBuffer.cpp needs a UL to UZ type change.
- Scheduler.hpp need to unset ERROR defined in windows.h so the macro is not substituted in the work::status::ERROR method.
- MemoryMonitor.cpp windows.h needs to be included before psapi.h. psapi.h has alot of windows specific types that we don't know about before including windows.h
- thread_pool.hpp replace unsigned long type with std::size_t.  This squares with the type for numThreads() and will allow ULL under windows and UL on linux.
- tested on windows and linux

Fixing various win32 errors that occur when trying to build

---

core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/BlockModel.hpp
core/include/gnuradio-4.0/Graph.hpp
core/include/gnuradio-4.0/Graph_yaml_importer.hpp
core/include/gnuradio-4.0/PluginLoader.hpp
core/include/gnuradio-4.0/Scheduler.hpp
core/test/qa_GraphMessages.cpp
core/test/qa_HierBlock.cpp
core/test/qa_Scheduler.cpp
core/test/qa_SchedulerMessages.cpp
core/test/qa_Settings.cpp
core/test/qa_grc.cpp
core/test/qa_plugins_test.cpp

This PR introduces a series of internal refactorings and ownership improvements for the `Graph`, `Edge`, and `SchedulerBase` subsystems, centred on robustness, reusability, and safe inspection of nested sub-graphs:
---
* **Ownership modernisation**
* Changed `Graph::_blocks` and `Edge::_sourceBlock/_destinationBlock` to use `std::shared_ptr<BlockModel>` instead of `unique_ptr` or raw pointers.
* This enables:
* **Safe flattening of nested sub-graphs** (copy-by-reference).
* **Thread-safe traversal and introspection**, especially across scheduler boundaries.
* **Consistent lifetime guarantees** during runtime reconfiguration (e.g., adoption, zombie cleanup).
* **New freestanding traversal functions** (replacing `forAllUnmanagedBlocks(...)`, `Graph::forEachBlock(...)`, etc.)
Introduced …

Refactor Graph/Scheduler ownership & traversal: shared_ptr<BlockModel>, freestanding forEachBlock/Edge, better diagnostics

---

core/include/gnuradio-4.0/thread/thread_pool.hpp

When users are on a platform that is not supported yet, report a proper error message instead of them getting a 'file not found' error.

Report an error message for unsupported platforms

---

core/test/qa_SchedulerMessages.cpp

kSetting is async, only evaluate its effect after message reply from scheduler.
Also no need to manually process messages since the scheduler already does that internally
We'll soon refactor how we wait for messages, but this should fix the CI asap.

qa_SchedulerMessages: fix flaky test

---

blocklib_generator/CMakeLists.txt
core/include/gnuradio-4.0/PluginLoader.hpp
core/include/gnuradio-4.0/thread/thread_affinity.hpp
core/test/qa_plugins_test.cpp

- blocklib_generator/CMakeLists.txt
- in windows we need to set PARSER_EXECUTABLE to gnuradio_4_parse_registrations.exe
- core/include/gnuradio-4.0/PluginLoader.hpp
- Conditional to allow loading of files ending in .dll on windows.
- core/include/gnuradio-4.0/thread/thread_affinity.hpp
- make inclusion of sys/resource dependent on not building on win32.
- core/test/qa_plugins_test.cpp
- Make conditional to use bad_plugin.dll instead of bad_plugin.so under windows.

win32: miscellaneous build fixes

---

CMakeLists.txt
core/include/gnuradio-4.0/BlockModel.hpp
core/include/gnuradio-4.0/Graph.hpp
core/include/gnuradio-4.0/Graph_yaml_importer.hpp
core/test/qa_SchedulerMessages.cpp

* This PR depends on https://github.com/gnuradio/pmt/pull/117 and https://github.com/gnuradio/pmt/pull/118
* pmt library `GIT_TAG` must be updated before merging 
Bump pmtv library version to resolve segfaults from std::vector reallocation
- Switch to the new pmtv::pmt implementation, which fixes the crash triggered when std::vector<pmtv::pmt> grew and reallocated under Clang 18/19.
- Add/keep a minimal “simple” test (first surfaced in “Get GRC Yaml tests”) as a regression to ensure the allocator/reallocation path stays stable.
- Additionally reserve vector capacity up front in hot paths to minimize relocations where possible.

Bump pmtv library version to resolve segfaults

---

core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/Port.hpp

The PR includes miscellaneous fixes in Port class.
* Fix: PortWrapper constructor checks were reversed
* Reason: both writerHandlerInternal and updateReaderInternal exist on Port, so the wrong static checks didn’t fail.
* Change: swap the checks and use requires constraints to conditionally enable appropriate function
(input -> updateReaderInternal, output -> writerHandlerInternal).
* Add std::move(portMetaInfo) for Port move constractor
* Implement Port::available() function (before it always returns 0). Use it in Block class where applicable.
* use isConnected instead of nReaders+nWriters > 0 check
* check for out-of-bounds writes to tags span in OutputSpan::processPublishTag

Port fixes

---

core/include/gnuradio-4.0/Block.hpp
core/include/gnuradio-4.0/Port.hpp
meta/include/gnuradio-4.0/meta/RangesHelper.hpp
meta/test/qa_RangesHelper.cpp

Implements a k-way merge view for forward ranges and apply it for the input tags pipeline so tags from multiple ports are merged into one view.

Add MergeView and apply to cross-port tag merging
