fair-acc/gnuradio4

include/graph.hpp, src/main.cpp
This is the correct default because the goal of merging nodes is to improve performance. If all intermediate results were returned (passed on) then the optimization would be greatly reduced.
ChangeLog:
* src/main.cpp (main): Adjust for different return type of merged node. (duplicate): New node type that copies its input to `Count` outputs.
* include/graph.h (any_node): Move into detail namespace. Implement the concept, though the check for process_one does not compile yet. (node): Make default constructor protected (never to be constructed directly). (merged_node): Remove connected output port from output_ports. (merged_node::process_one): Move the result from the connected output port from apply_left into apply_right and remove it from the tuple returned from the function.
=> Remove merged output ports

include/graph.hpp, include/nodes.hpp, src/main.cpp
by Matthias ... WIP before x-mas merge
=> redo port declarations

include/graph.hpp
... since there is an exception thrown if the nodes are not registered
Signed-off-by: Ralph J. Steinhagen <r.steinhagen@gsi.de>
=> removed noexcept from connect(...)

include/graph.hpp
... since there is an exception thrown if the nodes are not registered
Signed-off-by: Ralph J. Steinhagen <r.steinhagen@gsi.de>
=> removed more noexcept from connect(...)

include/node.hpp
include/ChangeLog:
* node.hpp: Add static assertions for can_process_simd on merged nodes. (merged_node::process_one): Reenable requires clause to disambiguate with simd overload.
There may be another way to disambiguate so that error messages can be improved again. I have not thought much about it, though.
=> Ensure that merged nodes do not lose can_process_simd

.github/workflows/ci.yml
clang 15.0.7 seems to have introduced a compile bug
=> fix clang to 15.0.6 and added clang 16

include/node.hpp, include/utils.hpp
Improve inner loop in `work` functions. Also resolves a warning.
=> dead store elimination

include/circular_buffer.hpp, test/qa_buffer.cpp
This addresses issue #68.
Added corresponding unit test and new least common multiple that fits both the size of the type, min memory page size, and minimum requested buffer.
for future reference/playing around: https://compiler-explorer.com/z/e9nPzbnx9
```cpp
template <typename T>
constexpr std::size_t align_with_page_size(const std::size_t min_size) noexcept {
const std::size_t pageSize = static_cast<std::size_t>(getpagesize());
const std::size_t elementSize = sizeof(T);
// least common multiple (lcm) of elementSize and pageSize
std::size_t lcmValue = (elementSize * pageSize) / std::gcd(elementSize, pageSize);
// adjust lcmValue to be larger than min_size
while (lcmValue < min_size) {
lcmValue += lcmValue;
}
return lcmValue;
}
```
=> fixes regression in circular_buffer<T> for non-power-of-two 'T'

CMakeLists.txt
N.B. most of the compiler warnings seem to have been fixed.
=> bumped pmt version to head of main

bench/bm_buffer.cpp, bench/bm_case1.cpp, bench/bm_history_buffer.cpp, include/history_buffer.hpp, include/node.hpp, include/port.hpp, test/app_plugins_test.cpp, test/qa_buffer.cpp, test/qa_dynamic_port.cpp, test/qa_filter.cpp, test/qa_scheduler.cpp, test/qa_settings.cpp
Continue removing remaining conversion's warnings after #79.
=> Remove remaining conversion's warnings.

include/graph.hpp, include/node.hpp, test/qa_settings.cpp
... used to store non-graph-processing information like UI block position etc.
=> added meta-information to node<T>

include/circular_buffer.hpp
... that rarely occurs while remapping the 'second_copy_addr' that may fail according to the docs:
"If another mapping already exists there, the kernel picks a new address that may or may not depend on the hint."
=> fixed Heisenbug in the circular_buffer<T>

include/circular_buffer.hpp, include/data_sink.hpp, include/thread_affinity.hpp, test/qa_data_sink.cpp, test/qa_settings.cpp
Fixes some of the code issues that sonarcube complains about.
Focuses on std::forward/std::move issues.
=> Sonarcloud fixes

test/blocklib/core/fft/fft.hpp
This PR includes thread-safe plan creation and destruction. 
Also it remove fftw_cleanup.
This PR should fix problems when several FFT blocks are created and destroyed or run in parallel.
=> Thread safe fftw plan creation and destroy. Remove fftw_cleanup.

.github/workflows/ci-meson.yml, .github/workflows/ci.yml
This PR contains the following changes in CI:
* Drop support of `clang-15`
* Add `gcc-13`
=> CI: Remove clang-15, add gcc-13.

include/node.hpp, include/settings.hpp, test/qa_settings.cpp
... to account for old- vs. new- vs. fwd settings.
Example:
```cpp
template<typename T, bool Average = false>
struct Decimate : public node<Decimate<T, Average>, SupportedTypes<float, double>, PerformDecimationInterpolation, Doc<R""(
@brief reduces sample rate by given fraction controlled by denominator
)"">> {
IN<T>                            in{};
OUT<T>                           out{};
A<float, "sample rate", Visible> sample_rate = 1.f;
void
settings_changed(const property_map & /*old_settings*/, property_map &new_settings, property_map &fwd_settings) noexcept {
if (new_settings.contains(std::string(fair::graph::tag::SIGNAL_RATE.shortKey())) || new_settings.contains("denominator")) {
const float fwdSampleRate = sample_rate / static_cast<float>(this->denominator); …
```
=> refactor settings_changed(old, new, fwd) & Decimate example block

blocks/basic/include/gnuradio-4.0/basic/common_blocks.hpp, blocks/fourier/include/gnuradio-4.0/fourier/fft.hpp, core/include/gnuradio-4.0/DataSet.hpp, core/include/gnuradio-4.0/Graph.hpp, core/include/gnuradio-4.0/Scheduler.hpp
* missing 'requires'
* sloppy '-1_UZ' cast
* erroneously use of std::move
=> fixes bugs reported by sonar

CMakeLists.txt, core/include/gnuradio-4.0/annotated.hpp, core/test/qa_Settings.cpp
Make it use the same version as opencmw-cpp.
=> Update to latest fmt

.github/workflows/ci.yml, CMakeLists.txt, algorithm/CMakeLists.txt, algorithm/include/gnuradio-4.0/algorithm/ImChart.hpp, algorithm/test/CMakeLists.txt, algorithm/test/example_ImChart.cpp, algorithm/test/qa_ImChart.cpp, core/include/gnuradio-4.0/BlockTraits.hpp, meta/include/gnuradio-4.0/meta/utils.hpp, sonar-project.properties
Pushed this already now because some of the commits might be useful for other PR in preparation (@ivan-cukic and @frankosterfeld emscripten version issues, @drslebedev signal source, @RalphSteinhagen FIR/IIR filter generator tool, ...)
Also added a new ImChart-feature that should be useful to cross-check some function w/o having to spin up a full GUI
Compact class for ASCII charting in terminal environments, supporting custom dimensions and styles.
ImChart enables the creation of various graph styles, including bar, braille, and point markers, directly within the terminal. Unicode braille characters are used for compact high-density visualisation, and supports dynamic scaling and some customisation. The primary use-case-focus is for basic visual debugging for library developers for …
=> Bumped to C++23, Emscripten 3.1.47, UT v2.0.0 and added ImChart

core/include/gnuradio-4.0/Scheduler.hpp
This PR fixes the problem with `Scheduler` when using only one thread (`n_batches = 1`) with execution Policy=multiThreaded.
If only one thread is used no need to wait updates from other threads, it will never happen.
=> Fix the problem in Scheduler

CORE_DEVELOPMENT_GUIDELINE.md
Minor edits to the core development guidelines
=> minor edits to core development guidelines

meta/include/gnuradio-4.0/meta/UncertainValue.hpp, meta/include/gnuradio-4.0/meta/formatter.hpp, meta/include/gnuradio-4.0/meta/utils.hpp, meta/test/CMakeLists.txt, meta/test/qa_UncertainValue.cpp, meta/test/qa_formatter.cpp
This pull request introduces the `UncertainValue<>` template class: 
```cpp
template<arithmetic_or_complex_like T>
struct UncertainValue {
T value       = static_cast<T>(0); /// mean value
T uncertainty = static_cast<T>(0); /// uncorrelated standard deviation
// [..]
};
```
Here, `uncertainty` represents the estimated measurement range within which the true value of a measurement lies, often expressed as a standard deviation in the context of a Gaussian (normal) distribution. This standard deviation quantifies the expected variability or spread of repeated measurements around the mean value, assuming a normal distribution of errors.
The class is designed to facilitate the propagation of uncertainties in calculations, a concept crucial in scientific, engineering, and real-time feedback …
=> Implementation of Propagation of Uncertainties

blocks/basic/include/gnuradio-4.0/basic/clock_source.hpp, blocks/basic/include/gnuradio-4.0/basic/common_blocks.hpp, blocks/basic/include/gnuradio-4.0/basic/selector.hpp, blocks/basic/test/qa_DataSink.cpp, blocks/basic/test/qa_selector.cpp, blocks/testing/include/gnuradio-4.0/testing/bm_test_helper.hpp, core/include/gnuradio-4.0/Block.hpp, core/include/gnuradio-4.0/Graph.hpp, core/include/gnuradio-4.0/Port.hpp, core/include/gnuradio-4.0/Scheduler.hpp, core/test/app_plugins_test.cpp, core/test/plugins/good_base_plugin.cpp, core/test/qa_DynamicBlock.cpp, core/test/qa_DynamicPort.cpp, core/test/qa_HierBlock.cpp, core/test/qa_Settings.cpp, core/test/qa_plugins_test.cpp, core/test/qa_port_array.cpp, meta/include/gnuradio-4.0/meta/utils.hpp
... as it is now part of the standard and supported by GCC and Clang.
=> replaced _UZ by c++23's UZ

algorithm/include/gnuradio-4.0/algorithm/ImChart.hpp, algorithm/include/gnuradio-4.0/algorithm/filter/FilterTool.hpp, algorithm/include/gnuradio-4.0/algorithm/fourier/window.hpp, blocks/basic/include/gnuradio-4.0/basic/DataSink.hpp, blocks/basic/include/gnuradio-4.0/basic/SignalGenerator.hpp, blocks/basic/include/gnuradio-4.0/basic/clock_source.hpp, blocks/basic/include/gnuradio-4.0/basic/common_blocks.hpp, blocks/basic/test/qa_DataSink.cpp, blocks/basic/test/qa_sources.cpp, blocks/testing/include/gnuradio-4.0/testing/TagMonitors.hpp, blocks/testing/include/gnuradio-4.0/testing/bm_test_helper.hpp, core/README.md, core/include/gnuradio-4.0/Block.hpp, core/include/gnuradio-4.0/CircularBuffer.hpp, core/include/gnuradio-4.0/Graph.hpp, core/include/gnuradio-4.0/Port.hpp, core/include/gnuradio-4.0/Scheduler.hpp, core/include/gnuradio-4.0/Tag.hpp, core/test/CMakeLists.txt, core/test/plugins/good_base_plugin.cpp, core/test/qa_Block.cpp, core/test/qa_DynamicPort.cpp, core/test/qa_HierBlock.cpp, core/test/qa_Scheduler.cpp, core/test/qa_Settings.cpp, core/test/qa_Tags.cpp, core/test/qa_buffer.cpp, meta/include/gnuradio-4.0/meta/utils.hpp, meta/test/qa_traits.cpp
... and their re-use in different unit-tests.
=> updated Tag[Source, Monitor, Sink]

CODE_OF_CONDUCT.md, CONTRIBUTING.md, CORE_DEVELOPMENT_GUIDELINE.md
This is a long overdue write-up on the proposed [core development guidelines](https://github.com/fair-acc/graph-prototype/blob/coreDevGuidelines/CORE_DEVELOPMENT_GUIDELINE.md) primarily targeted at maintainers, users that want to contribute to the core BlockLib, new Schedulers, or new features to the GNU Radio Core.
**Brief Summary:** *(please consult the [full text](https://github.com/fair-acc/graph-prototype/blob/coreDevGuidelines/CORE_DEVELOPMENT_GUIDELINE.md) and references for details)*
The Core Development Guidelines are centred around creating sustainable, efficient, and adaptable software, specifically for GNU Radio.
1. **Fit-for-Purpose Software**: The software should be adaptable to changing requirements, particularly for SDR applications.
2. **Friendly and Empathetic …
=> Core dev guidelines

blocks/http/include/gnuradio-4.0/http/HttpBlock.hpp, blocks/http/test/qa_HttpBlock.cpp
This ports the subscription management of `HttpBlock` to a messaging port based implementation, which was the last missing piece to remove the input streaming port, which should fix the flaky CI test, when building with coverage enabled.
The triggering of `GET`-style requests was already ported to messaging ports in a later commit of the initial PR.
=> Port HttpBlock subscription management to messaging ports

core/include/gnuradio-4.0/BlockTraits.hpp
opendigitizer's fails to compile otherwise
=> Add size() member to dummy span types

algorithm/include/gnuradio-4.0/algorithm/filter/FilterTool.hpp, algorithm/include/gnuradio-4.0/algorithm/fourier/fft.hpp, algorithm/include/gnuradio-4.0/algorithm/fourier/fftw.hpp, algorithm/test/qa_FilterTool.cpp, blocks/basic/include/gnuradio-4.0/basic/DataSink.hpp, blocks/basic/include/gnuradio-4.0/basic/Selector.hpp, blocks/basic/include/gnuradio-4.0/basic/clock_source.hpp, blocks/basic/include/gnuradio-4.0/basic/common_blocks.hpp, blocks/basic/test/qa_Selector.cpp, blocks/fourier/include/gnuradio-4.0/fourier/fft.hpp, blocks/testing/include/gnuradio-4.0/testing/ImChartMonitor.hpp, blocks/testing/include/gnuradio-4.0/testing/TagMonitors.hpp, blocks/testing/test/qa_UI_Integration.cpp, core/include/gnuradio-4.0/CircularBuffer.hpp, core/include/gnuradio-4.0/DataSet.hpp, core/include/gnuradio-4.0/Scheduler.hpp, core/include/gnuradio-4.0/annotated.hpp, core/test/qa_Block.cpp, core/test/qa_HierBlock.cpp, core/test/qa_Scheduler.cpp, core/test/qa_Settings.cpp, core/test/qa_buffer.cpp, core/test/qa_port_array.cpp
I have fixed nearly all of the warnings present. However, a few remain unfixed for specific reasons:
1) For warnings originating from `qa_port_array.cpp`, I have implemented fixes in a separate PR, as these are closely related to changes being made there.
2) Regarding the warnings in `ImChart`, I believe @RalphSteinhagen  would be the best person to tackle these.
=> Fix compiler warnings.

blocks/basic/include/gnuradio-4.0/basic/common_blocks.hpp, core/test/qa_DynamicBlock.cpp
Refactoring of MultiAdder block.
The error message is emitted and exception is thrown if number of input ports is changed after ports are already connected.
=> Refactoring of MultiAdder block

blocks/basic/include/gnuradio-4.0/basic/DataSink.hpp
Do not erroneously register the sink when the signal_name setting changes while the block is not started.
=> Datasink: Do not register block while not started

core/include/gnuradio-4.0/Settings.hpp
... addresses compile-time inefficiencies Settings handling, notably:
- Refining throw statement logic, reducing compile times from the baseline of 4m 16s to 2m 15s.
- Streamlining the Settings constructor, cutting down compile times further to 1m 17s.
Times were analysed on local i5-based machine using Clang's `-ftime-trace` feature and relying on `chrome://tracing/` flame-chart functionality.
base-line ([profile data](https://github.com/fair-acc/graph-prototype/files/14638023/exception_qa_Settings.tar.gz)):
optimising throw fmt-formatting ([profile data](https://github.com/fair-acc/graph-prototype/files/14638049/exception_qa_Settings.tar.gz):
optimising the `Settings` constructor ([profile data](https://github.com/fair-acc/graph-prototype/files/14638025/constructor_qa_Settings.tar.gz)): …
=> Reflection-related build-time optimisations

blocks/basic/include/gnuradio-4.0/basic/clock_source.hpp
Fix `qa_source` effective sample rate test.
=> Fix `qa_source` effective sample rate test.

bench/benchmark.hpp, core/include/gnuradio-4.0/Scheduler.hpp
*N.B. does not fix deprecation warnings regarding `std::shared_ptr<T>` `std::atomic<std::shared_ptr<T>>` as this may break API elsewhere. -> separate PR.*
=> fixes constexpr errors as reported by gcc14

.github/workflows/ci.yml
Should fix the docker container getting rebuilt even for PRs that don't change it.
=> CI: fix github treating bools as strings in ci yml

blocks/basic/include/gnuradio-4.0/basic/clock_source.hpp, blocks/fourier/include/gnuradio-4.0/fourier/fft.hpp, core/include/gnuradio-4.0/Block.hpp, core/include/gnuradio-4.0/DataSet.hpp, core/include/gnuradio-4.0/annotated.hpp
Small fixes needed for the opendigitizer refactoring.
=> Fixes for OD refactoring

.all-contributorsrc, CORE_DEVELOPMENT_GUIDELINE.md, README.md
@all-contributors 
please add @ivan-cukic for code, design, review.
please add @mattkretz  for code, design, review.
please add @wirew0rm  for code, design, review.
please add @frankosterfeld  for code, design, review.
please add @drslebedev   for code, design, review.
please add @RalphSteinhagen for code, design, review.
=> Update README.md for https://allcontributors.org/ bot

core/include/gnuradio-4.0/Graph_yaml_importer.hpp, core/include/gnuradio-4.0/Settings.hpp, core/test/qa_Settings.cpp, core/test/qa_grc.cpp
The PR consists of 2 commits:
Use std::hold_alternative instead of std::visit for PMTCompare + CtxSettings type test
Support of std::complex in Settings and YAML
=> CtxSettings type test, support std::complex for settings

core/test/qa_Settings.cpp
Add `TagSink` block which implements `processOne` to `autoUpdate` test.
=> Extend CtxSettings autoUpdate test with sink::processOne

bench/benchmark.hpp
- introduced `PerfEventHandler` RAII class.
- updated utility functions to use ranges.
- replaced recursive calls with fold expressions in `fake_modify`, `fake_read`, and related functions.
- fixed some minor SonarLint complains (e.g. '0l' vs '0L').
=> refactored PerformanceCounter

algorithm/include/gnuradio-4.0/algorithm/fourier/fftw.hpp
gcc is giving -Wsubobject-linkage warnings when gr::algorithm::FFTw is used as a member of a block because it says that fields such as fftwIn have internal linkage. This is caused by a lambda in the deleter of the std::unique_ptr used in InUniquePtr, etc. The warning can be removed by using a deleter struct instead of a lambda.
=> algorithm: fix gcc warnings in fftw wrapper

core/include/gnuradio-4.0/Block.hpp, core/test/qa_Block.cpp
Please first review https://github.com/fair-acc/gnuradio4/pull/392
Use `requestedWork` as a soft limit in the work function.
`work()` function should aim to honor the `requestedWork` value whenever feasible.
=> Use requestedWork as a soft limit in the work function

.all-contributorsrc, README.md
Seems like the contributor bot got stuck somewhere and only created the branch but not the PR, so I have to manually create it.
Sorry for the noise over in #397 
[skip ci]
=> docs: add dennisklein as a contributor for code

blocks/basic/include/gnuradio-4.0/basic/StreamToDataSet.hpp, blocks/basic/test/qa_StreamToDataSet.cpp
Modify the logic for when n_max is set: instead of generating multiple `DataSet` instances with up to `n_max` samples, generate only a single `DataSet` containing at most `n_max` samples, discarding any additional samples.
Also, add unit tests to verify this behavior.
=> StreamToDataSet: if n_max is set, produce only one DataSet

algorithm/include/gnuradio-4.0/algorithm/ImChart.hpp, blocks/soapy/include/gnuradio-4.0/soapy/Soapy.hpp, blocks/soapy/include/gnuradio-4.0/soapy/SoapyRaiiWrapper.hpp, core/include/gnuradio-4.0/TriggerMatcher.hpp
simple change, avoids linker errors
=> Function definitions in headers must be declared inline

blocks/basic/include/gnuradio-4.0/basic/clock_source.hpp
This PR addresses the issue with `ClockSource` not functioning correctly in infinite mode (`n_sample_max == 0`). Additionally, it resolves a problem where tags were not published properly when there was an early return due to insufficient slots in the output span.
=> Fix ClockSource to work correctly in infinite mode.

core/include/gnuradio-4.0/Scheduler.hpp, core/test/qa_Messages.cpp
The qa_Messages::"message passing via scheduler" test reproducibly fails on the (relatively resource constrained) CI runners for the scheduler's blocking execution strategy.
From the test output it could be observed, that the first get would timeout, then the set would fail because it would unexpectedly find the reply of the get command and then the second get would fail because it receives the reply of the first get command.
Because `checkReply` failed with an expect assertion instead of returning false, the retry parameter of the test was not working and the test would fail.
This increases the timeout for the tests from 2 to 4 seconds, reduces the timeout for the test that expects to timeout, to not increase execution times unnecessarily and changes the assertion of the received message …
=> qa_Messages: increase timeouts and allow retry

core/include/gnuradio-4.0/Block.hpp, core/include/gnuradio-4.0/Settings.hpp, core/test/qa_Messages.cpp
- Activate current context
- Get current Context
- Create new Context
- Get X Context
- Remove X Context
=> Add messages operations for handling Context

core/README.md, core/include/gnuradio-4.0/Block.hpp, core/include/gnuradio-4.0/Port.hpp, core/test/qa_Port.cpp
This PR includes:
* Sync and Async port semantic documentation
* Block class review/bug fixing
=> Sync and Async port semantic documentation

blocks/basic/include/gnuradio-4.0/basic/SyncBlock.hpp, core/include/gnuradio-4.0/Graph.hpp, core/include/gnuradio-4.0/PluginLoader.hpp, core/test/qa_GraphMessages.cpp
Add message handling for registry block types and registry known block parametrizations.
Related issue: https://github.com/fair-acc/opendigitizer/issues/247
=> Add message handling for block registry

blocks/basic/include/gnuradio-4.0/basic/DataSink.hpp
This pull request introduces the following updates and bug fixes to the DataSink block:
* Implemented `BaseListener` for `DataSetPoller`: Refactored the code to introduce a BaseListener class for DataSetPoller. This change reduces code duplication across listener implementations.
* Switched to blocking `reserve()` for DataSetPoller.
Notes:
We should consider revisiting the DataSink block, especially concerning the handling and terminology of the blocking mode:
* The current terminology for the blocking mode can be misleading. When set to `NonBlocking`, samples are dropped if there aren’t enough slots available for writing. This behavior might not be apparent to users, potentially leading to confusion. Consider renaming to  `enable_sample_dropping`.
* Blocking Behavior Impact: The current …
=> DataSink updates and bug fixing

.github/workflows/ci.yml, docker/Dockerfile
Improves the ccache integration in the CI. See individual commits for details.
=> Ccache followup

blocks/basic/include/gnuradio-4.0/basic/DataSink.hpp, blocks/testing/include/gnuradio-4.0/testing/ImChartMonitor.hpp
* ImChartMonitor: fixed xAxis numerical rounding error
* ImChartMonitor: added 'plot_merged_tags' option to suppress merged tags
* ImChartMonitor: added total sample counter
* DataSink: added missing `signalQuantity` initialisation
=> qFix in ImChartMonitor and DataSink.hpp

.github/workflows/ci.yml, blocks/testing/include/gnuradio-4.0/testing/ImChartMonitor.hpp
+ plus minor fix in ImChartMonitor to test the re-build
=> fix ccache ci.yml

blocks/basic/include/gnuradio-4.0/basic/StreamToDataSet.hpp, blocks/basic/test/qa_StreamToDataSet.cpp
This PR fixes a small bug in `StreamToDataset` block when `n_max==0`.
Additional unit tests were added.
=> StreamToDataset: fix issue when n_max==0 was not treated correctly.

algorithm/src/exprtk_example0.cpp, algorithm/src/exprtk_example1.cpp, algorithm/src/exprtk_example3.cpp, algorithm/src/exprtk_example4.cpp, core/include/gnuradio-4.0/Block.hpp, core/include/gnuradio-4.0/PmtTypeHelpers.hpp, core/include/gnuradio-4.0/thread/thread_pool.hpp, meta/include/gnuradio-4.0/meta/utils.hpp
https://sonarcloud.io/project/overview?id=fair-acc_graph-prototype
=> fixed top 16 SonarType warnings/errors

CMakeLists.txt, blocks/filter/include/gnuradio-4.0/filter/FrequencyEstimator.hpp, core/include/gnuradio-4.0/YamlPmt.hpp, core/test/qa_YamlPmt.cpp, docker/Dockerfile
enables better WASM+SDL3 integration downstream
=> bumped Emscripten to 4.0.8

core/include/gnuradio-4.0/YamlPmt.hpp, core/test/qa_YamlPmt.cpp
* added isIgnorableLine(sv) to skip lines that are empty, w/ only non-printable characters, or w/ only a comment
* added trimming to unquoted strings that ignore the comment and leading/trailing spaces.
* minor `std::source_location` unit-test helper cleanups
=> fix yaml-parser corner cases

meta/include/gnuradio-4.0/meta/formatter.hpp
Make getIsoTime accept any time-points
This fix is needed for OD.
=> Make getIsoTime accept any time-points
